### ISSUE TITLE
Ballgown object 

### ISSUE THREAD

**Issue by vitaly001** [alyssafrazee/ballgown#101]
Is it possible to save ballgown object as separate file for use in future?

**Comment by JMF47** [comment]
Not sure if this is what you mean, but you can always do 
```
save(bg, file="bg.rda")
```

**Comment by vitaly001** [comment]
Thank you, and how I can read it back?

**Comment by JMF47** [comment]
```
load("bg.rda")
```
:)

**Comment by vitaly001** [comment]
Indeed 😀.

**Comment by vitaly001** [comment]
Dear Jack,
Could you please tell me if it possible to separate up-regulate and
down-regulated transcripts with stattest function? and run plotTranscript
function using geneNames?
Thank you very much,

**Comment by JMF47** [comment]
When you talk about up and down regulation, I would assume that you have a reference group vs a treatment group? If so, you could use stat test to find the differential expression that have statistical significance. Finding the direction of regulation would simply require looking at average expression difference between control and treatment of the transcripts that stat test deems significant. You can use plot Transcript how you will after you obtain the list of transcripts you are interested in.

**Comment by vitaly001** [comment]
Thank you for you help. I can do it this way but it will take time and
require the running each transcript one by one. Is it possible to automate
this process(some undocumented way of stattest and plotTranscripts)?
Thank you,
Vitaly

**Comment by JMF47** [comment]
stattest does it simultaneously to either genes, transcripts, exons, or introns. 

```
stattest(gown = NULL, gowntable = NULL, pData = NULL, mod = NULL,
  mod0 = NULL, feature = c("gene", "exon", "intron", "transcript"),
  meas = c("cov", "FPKM", "rcount", "ucount", "mrcount", "mcov"),
  timecourse = FALSE, covariate = NULL, adjustvars = NULL, gexpr = NULL,
  df = 4, getFC = FALSE, libadjust = NULL, log = TRUE)
``` 

As for plotTranscript, it takes one gene at a time. Just use an apply function
```
lapply(genes, plotTranscript, bg)
```

**Comment by vitaly001** [comment]
Thank you. genes object is a list of genes?
Vitaly

**Comment by JMF47** [comment]
Yup!

**Comment by vitaly001** [comment]
Thank you

**Comment by JMF47** [comment]
No problems!

**Comment by vitaly001** [comment]
One more question. It show the transcripts only for the first sample. How
can I define the sample or push it to show all samples together
(like sample=c('OLD_PLUS', 'OLD_MINUS', 'YOUNG_PLUS', 'YOUNG_MINUS'))
Thank you,
Vitaly

**Comment by JMF47** [comment]
If you do `?plotTranscripts` you will find
```
plotTranscripts(gene, gown, samples = NULL, colorby = "transcript",
  meas = "FPKM", legend = TRUE, labelTranscripts = FALSE, main = NULL,
  blackBorders = TRUE, log = FALSE, logbase = 2, customCol = NULL,
  customOrder = NULL)
```

`samples` is vector of sample(s) to plot. Can be 'none' if only one plot (showing transcript structure in gray) is desired. Use sampleNames(gown) to see sample names for gown. Defaults to sampleNames(gown)[1].

**Comment by vitaly001** [comment]
Dear Jack,
I'm really sorry, but I still do not understand something. I read the
description of the function and here a few problems. When I run it for
single gene it work well, for example:

plotTranscripts(gene="Cdkn2a", gown = bg, samples =c('OLD_PLUS',
'OLD_MINUS', 'YOUNG_PLUS', 'YOUNG_MINUS'), colorby = "transcript",
                meas = "FPKM", legend = TRUE, labelTranscripts = TRUE, main
= NULL,
                blackBorders = TRUE, log = FALSE, logbase = 2, customCol =
NULL,
                customOrder = NULL)

However, when I try to lapply to list of genes, according to your advice,
it defaulting to the sample OLD_MINUS, which is the first in the list of
sampleNames(bg).

lapply(list_of_genes, plotTranscripts, bg)

If I want to add argument samples, you can see below what I'm doing,

lapply(list_of_genes, plotTranscripts(samples = c('OLD_PLUS', 'OLD_MINUS',
'YOUNG_PLUS', 'YOUNG_MINUS'), bg))

I got next response:
 Error in plotTranscripts(samples = c("OLD_PLUS", "OLD_MINUS",
"YOUNG_PLUS",  :
  argument "gown" is missing, with no default

 I can solve the problem with for loop:

for (i in list_of_genes) {plotTranscripts(gene= i, gown= bg, samples
=c('OLD_PLUS', 'OLD_MINUS', 'YOUNG_PLUS', 'YOUNG_MINUS'), colorby =
"transcript",
                                          meas = "FPKM", legend = TRUE,
labelTranscripts = TRUE, main = NULL,
                                          blackBorders = TRUE, log = FALSE,
logbase = 2, customCol = NULL,
                                          customOrder = NULL) }

However, I do not know how I can solve it with lapply.
Sorry so much for bothering you.
Best regards,
Vitaly

**Comment by JMF47** [comment]
What you need to do is actually:

```
lapply(list_of_genes, plotTranscripts, gown=bg, samples = c('OLD_PLUS', 'OLD_MINUS',
'YOUNG_PLUS', 'YOUNG_MINUS') )
```

The syntax for apply takes a bit of getting used to. All the additional arguments come after potTranscripts. No worries, everyone has to learn at some point how to use apply!

**Comment by vitaly001** [comment]
Thank you very much

**Comment by vitaly001** [comment]
Jack one more question, is it possible to use gene_name instead of gene_id
with plotTranscripts function?
Thank you,
Vitaly

**Comment by vitaly001** [comment]
Hi Jack,
Could you please help me to understand something about ballgown.
I run the analysis and now compare the FPKM value for transcripts and
genes. I don't understand the huge difference between the value I found.
For example if only single transcript is found it is equal to gene level
expression. However if multiple transcripts were found the FPKMs are quite
different. For example take a look at data in sample.xlsx file attached to
the email.
I hope you can help me.
Thank you,
Vitaly
