### ISSUE TITLE
How can I do Differential expression analysis if I don't have biological repeat?

### ISSUE THREAD

**Issue by yangguang8112** [alyssafrazee/ballgown#105]
# Wrong information
There must be at least two replicates per group. Make sure covariate is categorical; if continuous, consider the timecourse option, or specify your own models with mod and mod0.

**Comment by alyssafrazee** [comment]
The information from the docs is correct. It is not possible to use
stattest when
you only have one sample or replicate per condition. You cannot perform
statistical inference without replicates. (It is ok to use technical
replicates! But, as the documentation states, you must have more than 1).

If you want, you can rank the genes/transcripts by fold change, for
example, by calculating log2(FPKM_rep1) - log2(FPKM_rep2), and you may be
able to get some useful information that way! But without replicates, you
can not perform statistical inference, so you can't calculate p-values,
confidence intervals, standard errors or anything like that. (It does not
make sense to estimate variability when you have only one item). This is
true for Ballgown and any other software you might use for this problem.
