### ISSUE TITLE
stattest by using modified FPKM file? 

### ISSUE THREAD

**Issue by atasub** [alyssafrazee/ballgown#107]
Hi,

I have applied different low abundance gene filtering (not rowVars filtering) on the expression data (FPKM) and now would like to do the stattest by using this filtered expression data. However, I do not know how to implement this data to the stattest function in Ballgown.
If you could help me, I would be grateful.

Thank you.
Burcu

**Comment by alyssafrazee** [comment]
I assume you have created a new isoform-level expression matrix using something like this (I made up the example of "sum of FPKMs > 7", just as a theoretical thing different from `rowVars`):

```r
filtered_expr_data = texpr(bg)[rowSums(texpr(bg)) > 7,]
```

I would actually recommend creating an entirely new ballgown object with the filtering, which can then be used in `stattest` directly, as follows (filling in the `...` with whatever arguments you need for `stattest`:

```r
bg_filt = subset(bg, "rowSums(texpr(bg)) > 7", genomesubset=TRUE)
results = stattest(bg_filt, ...)
```

the key is to create a new _ballgown_ object with your filtered data that you can then pass to `stattest`.

Hope this helps!
