### ISSUE TITLE
Issues with Nature protocol with HISAT, StringTie and Ballgown 

### ISSUE THREAD

**Issue by ivaliente** [alyssafrazee/ballgown#108]
Hello,

We are going through the paper publish by Salzberg group with Chromosome X (doi:10.1038/nprot.2016.095). We have no problems until we get to ballgown and get a transcript table (step 16) that differs from the authors. We got a feature column instead of the transcript name column for the paper. It looks like we are missing something a connection between the data and the gene name command or something that we are missing. I'm pretty sure we're doing something wrong but we don't know what it is. Thanks for any suggestion

**Comment by alyssafrazee** [comment]
Hey @ivaliente, could you please post this question along with a few more details at support.bioconductor.org? There's a wider community that can help you there (the issues here are for potential bugs with the ballgown software). 

When you do post your question there, could you include the output you got as well as the exact commends you ran to get the output? 

Thanks! Closing for now but feel free to reopen if there is a software bug here we should be fixing.
