### ISSUE TITLE
What is the reference for Fold change

### ISSUE THREAD

**Issue by XuewenWangUGA** [alyssafrazee/ballgown#109]
For the differential expression, the ballgown will calculate the fold change , referred to as "fc" . I am confused what is the the reference for Fold change during comparison. 

For an example: four samples, two treatments (treatment C, and treatment D), two duplicate for each sample (s#)
Sample_id Treatment
s1-a D
s2-b D
s3-a C
s4-b C

The question is what Ballgown will use as a reference or control ? It is D or C? 
 If to use treatment "C" as the reference, e.g. the fc should be 2. 
but if to use treatment "D" as the reference, e.g. the fc should be 1/2. 
How to set the reference during comparison? It seems not clear in the manual and demonstrated data.
Thanks.

**Comment by alyssafrazee** [comment]
The reference is C. Ballgown uses linear models under the hood, so it
calculates the reference group for factors the same way lm would, using the
first category alphabetically. You can also verify empirically!

**Comment by FawziYassine** [comment]
What is the formula at Ballgown news to calculate fc?

**Comment by FawziYassine** [comment]
What is the formula that Ballgown  uses to calculate fc?

**Comment by alyssafrazee** [comment]
@FawziYassine if you are talking about the output of `stattest` with `getFC` set to `TRUE`, then the answer is no, it does not use a log. The fold change returned is the exponentiated (base 2) coefficient of the `group` variable in the linear model fit to that gene predicting expression given that group variable plus any adjustment variables. 

You should be able to verify that the fold changes are not log-transformed empirically in the output (there should not be any negative values; all down-regulated genes should have FC < 1, all up-regulated genes should have FC > 1). 

Hope this helps!
