### ISSUE TITLE
ballgown function plotTranscripts cuts off expression measurements

### ISSUE THREAD

**Issue by thenolfar** [alyssafrazee/ballgown#120]
I recently started using ballgown for analysis of RNA-seq data.
When I use the function plotTranscripts(), it cuts off the scale numbers for the expression above the bar, shown in the picture below.

My call of the function is the following:

`plotTranscripts(gene='MSTRG.36198', gown=bgObject, samples='66990', 
                meas='FPKM', colorby='transcript', 
                main='transcripts from gene MSTRG.36198: MZn2, FPKM')
`

![mstrg36198](https://user-images.githubusercontent.com/10518637/32701922-72cfc6d0-c7de-11e7-8d6e-6fe2dc541412.png)

I am running ballgown from an R script which I run with the source command inside the command line version of R on an archlinux server (4.10.11-1-ARCH). The R version is 

> R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"

Any help would be greatly appreciated.

**Comment by JMF47** [comment]
I've located the bug in `plotTranscripts` and have a fix. However, I need to propagate the changes to the ballgown package on Bioconductor. It might take a little bit with the move to the new system. Thanks!
