### ISSUE TITLE
visualization of sample distance 

### ISSUE THREAD

**Issue by Jwaj** [alyssafrazee/ballgown#124]

**Comment by Jwaj** [comment]
Hi,

I am wondering whether is there any codes in ballgown packages to makes plots to visualize sample distance (between samples in control group), for example PCA plot or heatmap plot.

Thanks
Jwaj

**Comment by JMF47** [comment]
Not so far, but I would recommend using functions like `heatmap.2` on the normalized counts.

**Comment by Jwaj** [comment]
Thank you very much for promot reply.

I am very new with R, do you have any script for the function heatmap.2


Best

**Comment by JMF47** [comment]
It's part of the package `gplots`
https://www.rdocumentation.org/packages/gplots/versions/3.0.1/topics/heatmap.2
