### ISSUE TITLE
some question about multigroup analysis(4 groups)

### ISSUE THREAD

**Issue by milkcookie** [alyssafrazee/ballgown#125]
Dear all:
    Recendly, I used ballgown to do RNA_seq, but I have 4 periods with my sample, I also have sex analysis, so I want to know how to analysis the diff between the four periods, and the same periods but diff sex.
which function I  should use in ballgown. please detailedly if you can.
Thanks

**Comment by alyssafrazee** [comment]
Hi there, thanks for your question! This repository is for bug reports in
the ballgown package itself. For advice on how to use the software and
conduct analysis, we recommend support.bioconductor.org -- there is a tag
for ballgown. Thanks!
