### ISSUE TITLE
Gene name in the gexpr(bg) function

### ISSUE THREAD

**Issue by Jwaj** [alyssafrazee/ballgown#127]
Hi everyone,

I was wondering, is that possible to get gene name (LOC) instead gene_id (MSTRG) with gexpr(bg) function or other way to get FPKM value for gene expression (all samples) either with ballgown or Stringtie.

Thanks

**Comment by JMF47** [comment]
What reference file are you feeding into stringtie? Does the annotation file have both gene name (LOC) and gene_id (MSTRG) for each entry?

**Comment by Jwaj** [comment]
I used .gtf file for annotation and it include gene name (LOC) and gene_id (MSTRG). with transcript is fine I have all information but with gene expression just gene_id (MSTRG).

**Comment by JMF47** [comment]
The most straightforward would be to construct a table linking gene name and gene id from the annotation file. Something like:
```
library(rtracklayer)
reference = import('reference.gtf')
mapping = data.frame(gene_id=reference$gene_id, gene_name=reference$gene_name)
mat = match(rownames(gene_counts), mapping$gene_id)
rownames(gene_counts) = mapping$gene_name[mat]
```
where `gene_counts` is your counts matrix with gene_id (MSTRG) names.

**Comment by Jwaj** [comment]
Thank you very much 

It is not working with me because gene_id(MSTRG) is made by stringtie is not same in ID in annotation file. I have attached an example of gene count and annotation (gtf). 

I have gene id (MSTRG) and gene_name (LOC) from transcript count, is that possible find match between gene_id between gene count and transcript count(isoform) then call LOC number.

Best

**Comment by karlaarz** [comment]
Hi everyone,

I tried to construct the table linking gene name and gene id following the script, but it appears the next error: 

`Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
In addition: Warning message:
non-unique values when setting 'row.names':`

Is there any suggestion to solve this?

Thanks!

**Comment by alyssafrazee** [comment]
hey @karlaarz, could you please post a small reproducible example of how you got this error? what did your input data look like and what code were you running? a small reproducible example where you can show all of the input data that gave the error would be ideal.

**Comment by karlaarz** [comment]
Hi @alyssafrazee. I found it was a typo and it worked after I changed it.  However, when I review the output file, the new gene_name is "NA" for all the genes id that used to be "MSTRG" even though most of those genes are already known genes. 

How can this be solved?

Thanks!

**Comment by alyssafrazee** [comment]
Even though this is a different problem, we can't help you very much or determine whether this is a ballgown bug without a small reproducible example showing the code and data you used :)

**Comment by karlaarz** [comment]
Hi @alyssafrazee. I got ballgown's data from the stringtie analysis following its manual. I used my merged gtf file as reference to obtain the ballgown output. The code that I used for the ballgown analysis was:

`setwd("C:/Users/mine/Documents/R/de_analysis/ballgown/")
require(ballgown)
library(ballgown)
library(genefilter)
library(dplyr)
library(devtools)
library('rtracklayer')

data_directory = 'C:/Users/mine/Documents/R/de_analysis/ballgown/'
bg = ballgown(dataDir=data_directory, samplePattern='*_ballgown', meas='all')
transcript_expression = texpr(bg, 'all')
gene_exp = gexpr(bg)
reference <- 'final_merged_ref.gtf'
mygtf <- import(reference)
mapping = data.frame(gene_id=mygtf$gene_id, gene_name=mygtf$gene_name)
mat = match(rownames(gene_exp), mapping$gene_id)
rownames(gene_exp) = mapping$gene_name[mat]`

The outputs:
`head(transcript_expression)
t_id chr strand start   end          t_name num_exons length  gene_id gene_name cov.SRR7460835_ballgown FPKM.SRR7460835_ballgown
1    1   1      + 11441 12227      MSTRG.50.1         2    449 MSTRG.50         .                       0                        0
2    2   1      + 11601 14539      MSTRG.50.2         4   1890 MSTRG.50         .                       0                        0
3    3   1      + 11869 14539 ENST00000456328         3   1787 MSTRG.50   DDX11L1                       0                        0
`

`head (mygtf)
GRanges object with 6 ranges and 9 metadata columns:
      seqnames        ranges strand |    source       type     score     phase     gene_id   transcript_id exon_number   gene_name     ref_gene_id
         <Rle>     <IRanges>  <Rle> |  <factor>   <factor> <numeric> <integer> <character>     <character> <character> <character>     <character>
  [1]        1 990577-994136      * | StringTie transcript      1000      <NA>     MSTRG.1       MSTRG.1.1        <NA>        <NA>            <NA>
  [2]        1 990577-994136      * | StringTie       exon      1000      <NA>     MSTRG.1       MSTRG.1.1           1        <NA>            <NA>
  [3]        1 983348-986189      * | StringTie transcript      1000      <NA>     MSTRG.2       MSTRG.2.1        <NA>        <NA>            <NA>
  [4]        1 983348-986189      * | StringTie       exon      1000      <NA>     MSTRG.2       MSTRG.2.1           1        <NA>            <NA>
  [5]        1 966497-975108      + | StringTie transcript      1000      <NA>     MSTRG.3 ENST00000379410        <NA>     PLEKHN1 ENSG00000187583
  [6]        1 966497-966614      + | StringTie       exon      1000      <NA>     MSTRG.3 ENST00000379410           1     PLEKHN1 ENSG00000187583
  -------`

`head (gene_exp )
 FPKM.SRR7460835_ballgown FPKM.SRR7460842_ballgown FPKM.SRR7460844_ballgown FPKM.SRR7460845_ballgown FPKM.SRR7460846_ballgown
<NA>                      1.6982048               2.26280667                2.3904810               2.46184265                1.6212476
AC125616.1                0.0000000               0.41359281                0.0000000               0.00000000                0.1476823
CABP1                     1.7401911               0.91001784                1.0375400               0.63634922                1.5444641
<NA>                      5.4776247               7.10068253                5.1296968               5.18351588                5.5239104
TRIAP1                    2.6770433               2.50850457                3.3045814               4.30450752                3.7344454
RPL31P52                  0.7739150               0.63867400                0.6610900               0.93518100                1.0675630
<NA>`
