### ISSUE TITLE
error reading ballgown object

### ISSUE THREAD

**Issue by LJLeach** [alyssafrazee/ballgown#128]
I have tried to read in the table count information for my samples created by Stringtie according to the protocol in the tutorial from the Pertea (2016) paper. I receive the following error:
Tue Jan 30 13:15:04 2018
Tue Jan 30 13:15:04 2018: Reading linking tables
Tue Jan 30 13:15:05 2018: Reading intron data files
Tue Jan 30 13:15:08 2018: Merging intron data
Tue Jan 30 13:15:09 2018: Reading exon data files
Tue Jan 30 13:15:17 2018: Merging exon data
Tue Jan 30 13:15:18 2018: Reading transcript data files
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 70810 did not have 12 elements
In addition: Warning messages:
1: package ‘dplyr’ was built under R version 3.3.3 
2: package ‘devtools’ was built under R version 3.3.3 

The traceback was not helpful to me as follows...
> traceback()
8: scan(file = file, what = what, sep = sep, quote = quote, dec = dec, 
       nmax = nrows, skip = 0, na.strings = na.strings, quiet = TRUE, 
       fill = fill, strip.white = strip.white, blank.lines.skip = blank.lines.skip, 
       multi.line = FALSE, comment.char = comment.char, allowEscapes = allowEscapes, 
       flush = flush, encoding = encoding, skipNul = skipNul)
7: read.table(file, header = TRUE, sep = "\t", colClasses = cc, 
       quote = "")
6: .readTranscript(f, meas)
5: ballgown(samples = samples, pData = pheno_data) at rnaseq_ballgownLL.R#16
4: eval(expr, envir, enclos)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("rnaseq_ballgownLL.R")

The phenotype data file was read into R correctly as 

> pheno_data
  ids population
1  HJ     China1
2  HL     China2
3  LS     China3
4  V7     China4

I have checked the gtf files and ctab for each sample and cannot find a problem with the format. 

Also, I was able to run the tutorial data and read in the bg object correctly, so the problem must relate to my input files somehow.
The code used was as follows:

library(ballgown)
library(RSkittleBrewer)
library(genefilter)
library(dplyr)
library(devtools)

inputdir="C:/Users/leachlj/Documents/Data/Potato/RNA_seq_Round2/BallGownAnalysis/"
pheno_data_file=paste(inputdir,"round2_rnaseq.txt", sep="");

## Read phenotype sample data
pheno_data <- read.csv(pheno_data_file)

## Read in expression data to create a BallGown object
samples<-c("HJ","HL","LS","V7")
bg_pot <- ballgown(samples=samples, pData=pheno_data)

Can anyone help me to resolve this please? Thank you for any advice.

**Comment by alyssafrazee** [comment]
it looks like this is an issue with the input data rather than the ballgown library itself. since this question is repeated over at support.bioconductor.org, let's move discussion over to that post! https://support.bioconductor.org/p/105425/
