### ISSUE TITLE
stattest on only known genes

### ISSUE THREAD

**Issue by unfashionable** [alyssafrazee/ballgown#129]
Hi,

I want to apply stattest on only the known genes, which is around 40K. 

I know when use the "subset" function, you can select the gene id. But, when I give it 40K gene ids, it won't output anything.

The ballgown object contains 70K transcripts, I really just want to get the known genes.

Another approach I can do is to apply stattest on all the genes, then parse the result to select only known genes. But that could comprise the q-value calculation, since q-value depends on the number of hypothesis test. I can calculate the q-value myself, the question will then be what the q-value formula is for ballgown.

Any ideas on how to select only the known genes?

Yichao

**Comment by alyssafrazee** [comment]
A couple recommendations:

1. You didn't specify what your `subset` command was. If you want to subset to a list of 40K gene IDs, I would recommend putting those 40K gene IDs into a vector or getting them into vector format by reading them in from a file or something, e.g.: `my_gene_ids = c("gene_1", "gene_2", ..., "gene_n")`, and then using the %in% operator: e.g., `known_bg = subset(bg, "gene_id %in% my_gene_ids")`. I would not recommend passing a `cond` string of 40K gene IDs.
2. You can also apply stattest on all the genes and then select only the known genes from that result -- and you're right, the q-values will be off. The q-value formula for ballgown is straightforward though! You can see it here: https://github.com/alyssafrazee/ballgown/blob/master/R/stattest.R#L334. So, if you have your data frame `known_gene_results`, you can re-adjust the p-values to get q-values for just the known genes by doing `p.adjust(known_gene_results$pval, "fdr")`. 

Hope this helps,
Alyssa
