### ISSUE TITLE
Number of transcripts in bg object is different from the number in canonical gtf file

### ISSUE THREAD

**Issue by HHHit** [alyssafrazee/ballgown#130]
I was trying to use Polyester which requires ballgown object as input. I generated my ballgown objects based on the **Tablemaker** results. The number of transcripts in the ballgown object is **198838**. While in the canonical gtf, **Homo_sapiens.GRCh38.87.mod.gtf**, the number of transcripts is **197898**. I don't quite understand why it happens. Am I using the wrong canonical gtf file?

**Comment by alyssafrazee** [comment]
Tablemaker results are generally created using Cufflinks. You didn't say whether you used Cufflinks or how you ran it, but the Tablemaker results often are from a de novo transcript assembly based on input reads. De novo assemblies can have more transcripts than the canonical GTF file. (Cufflinks assemblies can also be based on an input GTF, or "guided" -- i.e., a mix of an input GTF + de novo transcripts created from the input reads). In any case, if the Cufflinks assembly was de novo or guided (or even created strictly from a GTF but a different _version_ of the human genome canonical gtf, i.e. GRCh37 or hg19) then it also might have more transcripts than the GRCh38 GTF you mention in your comment. You could learn more by examining the transcripts that are present in one but not the other.

Also, one side note is that Polyester does not require ballgown as input. (You can optionally use a ballgown object as input to make your simulation more realistic, though! Just note that you can use Polyester without Ballgown if you would like).
