### ISSUE TITLE
Can't add Transcript name (NM_xxx)

### ISSUE THREAD

**Issue by LiangMa2017** [alyssafrazee/ballgown#132]
Hello, my Ballgown input files using stringtie, of which, gtf as shown below has transcript ID as NM_xxx.
-------------------
>
chr1    StringTie       exon    134773  139696  1000    -       .       gene_id "NR_039983"; transcript_id "NR_039983"; exon_number "1"; ref_gene_name "LOC729737"; cov "0.166415";
chr1    StringTie       exon    960587  960800  1000    +       .       gene_id "NM_198317"; transcript_id "NM_198317"; exon_number "1"; ref_gene_name "KLHL17"; cov "0.000000";
chr1    StringTie       exon    961293  961552  1000    +       .       gene_id "NM_198317"; transcript_id "NM_198317"; exon_number "2"; ref_gene_name "KLHL17"; cov "0.000000";
-------------------
But the name can't be shown. How can I load the NM_xxx to my data?
> ballgown::transcriptNames(bg)[1:100]
           1            2            3            4            5            6
      "rna0"       "rna1"       "rna3"       "rna2"       "rna4"       "rna5"

Thank you!

**Comment by LiangMa2017** [comment]
gtf ID like gene_id "NM_198317"; transcript_id "NM_198317"; are also not shown in bg_table. I have no idea how to add NM number to the table.

>bg = ballgown(samples=as.vector(pheno$path),pData=pheno)
> head(bg_table)
  t_id          chr strand start   end t_name num_exons length gene_id
1    1 NC_000001.11      + 11874 14409   rna0         3   1652 MSTRG.1
2    2 NC_000001.11      - 14362 29370   rna1        11   1769 MSTRG.2
3    3 NC_000001.11      - 17369 17391   rna3         1     23 MSTRG.3
4    4 NC_000001.11      - 17369 17436   rna2         1     68 MSTRG.3
5    5 NC_000001.11      - 17409 17431   rna4         1     23 MSTRG.3
6    6 NC_000001.11      + 29926 31295   rna5         3    538   gene3
     gene_name cov.DMSO-earlyG1-1 FPKM.DMSO-earlyG1-1 cov.DMSO-earlyG1-2
1      DDX11L1                  0                   0                  0
2       WASH7P                  0                   0                  0
3    MIR6859-1                  0                   0                  0
4    MIR6859-1                  0                   0                  0
5    MIR6859-1                  0                   0                  0
6 LOC107985730                  0                   0                  0

**Comment by JMF47** [comment]
How did you create `bg_table`?

**Comment by JMF47** [comment]
Hi @LiangMa2017, could you post the code for how you created the `bg_table` object?
Could you also tell me how many entries the `gtf` file has, as well as `dim(indexes(bg)$t2g)`? Thanks!

**Comment by LiangMa2017** [comment]
Thank you for your response. Sorry I missed one line below for creating the bg_table.
>bg = ballgown(samples=as.vector(pheno$path),pData=pheno)
>bg_table = texpr(bg, 'all')
>head(bg_table)

I exactly use the reference and gtf files used in the Nature Protocol paper. 
> dim(indexes(bg)$t2g)
[1] 180516      2
I'm not sure you want me list the stringtie merged gtf line number, please let me know if otherwise.
$ wc -l stringtie_merged.gtf
630963 stringtie_merged.gtf

It is weird that the NM_xxx has been shown using the Nature Protocol samples. I have no idea what is wrong with my samples.
>bg_chrX <- ballgown(dataDir = "ballgown", samplePattern="ERR", pData=pheno_data_file)
>ballgown::transcriptNames(bg_chrX)[3418]
3418
 "NM_171998"

**Comment by JMF47** [comment]
Great, thanks for the info there.
Can you also run
```
reference = rtracklayer::import("stringtie-merged.gtf")
transcripts = reference[reference$type=="transcript"]
length(reference)
length(transcripts)
```

Thanks,
Jack

**Comment by LiangMa2017** [comment]
Thank you, Jack. Here is the output:
> reference = rtracklayer::import(paste0(path1,"out/ballgown/stringtie_merged.gtf"))
Warning message:
In if (is.null(x)) x <- character() :
  closing unused connection 3 (/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/stringtie-merged.gtf)
> transcripts = reference[reference$type=="transcript"]
> length(reference)
[1] 630961
> length(transcripts)
[1] 69157

**Comment by JMF47** [comment]
Hmm, there's a bit of discrepancy between the size of `dim(indexes(bg)$t2g)` and `length(transcripts)`, the number of rows in the former should equal the length of latter. Can you show me the command you used to run `stringtie`?

**Comment by LiangMa2017** [comment]
Hi Jack,
Thanks for the explaining. I used the code from Nature Protocol paper (download from ftp://ftp.ccb.jhu.edu/pub/RNAseq_protocol), below is the stringtie part. I can send it to your personal email by attachment if needed.

## merge transcript file
echo [`date +"%Y-%m-%d %H:%M:%S"`] "#> Merge all transcripts (StringTie)"
ls -1 ${ALIGNLOC}/*.gtf > ${ALIGNLOC}/mergelist.txt

$STRINGTIE --merge -p $NUMCPUS -G  ${GTFFILE} \
    -o ${BALLGOWNLOC}/stringtie_merged.gtf ${ALIGNLOC}/mergelist.txt

## estimate transcript abundance
echo [`date +"%Y-%m-%d %H:%M:%S"`] "#> Estimate abundance for each sample (StringTie)"
for ((i=0; i<=${#reads1[@]}-1; i++ )); do
    sample="${reads1[$i]%%.*}"
    dsample="${sample%%_*}"
    sample="${sample%_*}"
    if [ ! -d ${BALLGOWNLOC}/${dsample} ]; then
       mkdir -p ${BALLGOWNLOC}/${dsample}
    fi
    $STRINGTIE -e -B -p $NUMCPUS -G ${BALLGOWNLOC}/stringtie_merged.gtf \
    -o ${BALLGOWNLOC}/${dsample}/${dsample}.gtf ${ALIGNLOC}/${sample}.bam
done

**Comment by JMF47** [comment]
can you print me the first 6 lines of the `pheno` table?
Trying to narrow down why `bg_table` doesn't only have 69,157 rows.

Thanks!

**Comment by LiangMa2017** [comment]
Thank you, Jack. Please check below.

Note that I changed the sample names after running stringtie. Then I run
ballgown separately using the short names. I'm not sure it will affect the
results.

> path1="/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/"
> pheno <- read.csv(paste0(path1, "dmso_phenotype.csv"),header=T)
> pheno
                ids    type
1    DMSO-earlyG1-1    dmso
2    DMSO-earlyG1-2    dmso
3 control-earlyG1-1 control
4 control-earlyG1-2 control

   path
1
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/ballgown_GRCh38/DMSO-earlyG1-1
2
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/ballgown_GRCh38/DMSO-earlyG1-2
3
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/ballgown_GRCh38/control-earlyG1-1
4
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/ballgown_GRCh38/control-earlyG1-2
>bg = ballgown(samples=as.vector(pheno$path),pData=pheno)
>bg
 ballgown instance with 180516 transcripts and 4 samples

**Comment by JMF47** [comment]
What does
```
list.files('/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/ballgown_GRCh38/DMSO-earlyG1-1')
```
look like?

**Comment by LiangMa2017** [comment]
Hi Jack,
Please check below. I see. the path is wrong! it should be
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/
DMSO-earlyG1-1

>
list.files('/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/ballgown_GRCh38/DMSO-earlyG1-1')
[1] "H9Fucci-DMSO-earlyG1-1-AAGAGGCA-TCTACTCT_S7_L006.gtf"
[2] "e2t.ctab"
[3] "e_data.ctab"
[4] "i2t.ctab"
[5] "i_data.ctab"
[6] "t_data.ctab"

**Comment by JMF47** [comment]
What is in
```
list.files('/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/DMSO-earlyG1-1')
```

If I understand you correctly, you should correct the path being supplied to in the `pheno` matrix:
```
bg = ballgown(samples=as.vector(pheno$path),pData=pheno)
```

**Comment by LiangMa2017** [comment]
Thank you, Jack.
Finally, we make it. All because of the path. May I ask is there any other
way to read in the pheno data instead of provide path, because I need to
get all the path and transfer the csv file to server, it is easy to get
wrong.

>list.files('/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/DMSO-earlyG1-1')
# [1] "DMSO-earlyG1-1.gtf" "e2t.ctab"           "e_data.ctab"
# [4] "i2t.ctab"           "i_data.ctab"        "t_data.ctab"

#re-run is as below
> path1="/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/"
> pheno <- read.csv(paste0(path1, "dmso_phenotype.csv"),header=T)
> pheno
                ids    type
1    DMSO-earlyG1-1    dmso
2    DMSO-earlyG1-2    dmso
3 control-earlyG1-1 control
4 control-earlyG1-2 control

        path
1
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/DMSO-earlyG1-1
2
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/DMSO-earlyG1-2
3
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/control-earlyG1-1
4
/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/control-earlyG1-2
> bg = ballgown(samples=as.vector(pheno$path),pData=pheno)
> bg
ballgown instance with 69157 transcripts and 4 samples
> dim(indexes(bg)$t2g)
[1] 69157     2
> reference =
rtracklayer::import(paste0(path1,"out/ballgown/stringtie_merged.gtf"))
> transcripts = reference[reference$type=="transcript"]
> length(reference)
[1] 630961
> length(transcripts)
[1] 69157
> ballgown::transcriptNames(bg)[1:100]
                  1                   2                   3
   4
        "NR_046018"         "NR_024540"         "NR_107062"
"MSTRG.10.1"
                  5                   6                   7
   8
       "MSTRG.11.1"         "NR_036051"         "NR_036266"
 "NR_036267"
                  9                  10                  11
  12
        "NR_036268"         "NR_026818"         "NR_026820"
 "NR_026822"
                 13                  14                  15
  16
     "NM_001005484"         "NR_039983"    "NR_106918_dup1"
"NR_107062_dup1"



Cheers!
Liang

**Comment by JMF47** [comment]
Glad we hunted it down!
As for an easier way, this might be less error prone:
[assuming there are no other folders in `baseDir` other than the stringtie output folders]
```
baseDir  = '/srv/gsfs0/projects/chetty/liangma1/test/rnaseq/rnaseq2/out/ballgown/'
bg <- ballgown(samples=list.files(baseDir), pData = pheno)
```

Cheers,
Jack

**Comment by LiangMa2017** [comment]
Thank you, Jack.
