### ISSUE TITLE
Ballgown error

### ISSUE THREAD

**Issue by Jiglov** [alyssafrazee/ballgown#135]
Hi, there,

I've tried my luck getting response on other closed issues (or trying to solve it using the answers):
first column of pData does not match the names of the folders containing the ballgown data. #113
https://github.com/alyssafrazee/ballgown/issues/113

and also
Unable to load data in #71
https://github.com/alyssafrazee/ballgown/issues/71

Couldn't solve the issue from answers, and since the issues were closed I assume I won't get a response.

So I'm putting a new post here:

I had an error when trying to use ballgown on HISAT2 aligned data, with stringtie created tables.
I followed the protocol in Pertea 2016 HISAT STRINGTIE BALLGOWN

First I've got this error:

Error in ballgown(samples = "D:/My RNA seq/HISAT2 STRINGTIE GTF files/ballgown",  : 
  first column of pData does not match the names of the folders containing the ballgown data.
In addition: Warning message:
In ballgown(samples = "D:/My RNA seq/HISAT2 STRINGTIE GTF files/ballgown",  :
  Rows of pData did not seem to be in the same order as the columns of the expression data. Attempting to rearrange pData...

In an attempt to solve it myself I read the previous posts in here (links are above).

And when trying to call the constructor without supplying the phenotype file I get the following message Error in ballgown(dataDir = ".", samplePattern = "mine") :
Something is wrong: are you missing .ctab files? Do extra files/folders (other than tablemaker output folders) match your samples/dataDir/samplePattern argument(s)?

When I ran Stringtie according to the paper on my own data, it created 5 .ctab files for 12 replicates, If i understand correctly replicate=sample.

In this case, in the paper they had also multiple samples and they get also 5 .ctab files, not sure what suppose to be correct 5 .ctab files per replicate or 5 .ctab files for all 12 replicates. In this case how do you create 5 per replicate running the same protocol from the paper?

I've tried running Stringtie to ballgown only step and it doesn't change the number of .ctab files, Is my stringtie stop after 1 replicate (that's what I suspect, just not sure)? If so how do I troubleshoot it?

Thanks.

**Comment by JMF47** [comment]
Hey there, apologies in advance of the brevity of this note (I'm traveling) - but you should have 5 .ctab files for each sample/replicate. Could you post the hisat and stringtie code you ran? Thanks!

**Comment by Jiglov** [comment]
"#Align with Hisat2 each replicate in each condition
hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL-1-I1_S4_L001_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL-1-I1_S4_L002_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL-1-I1_S4_L003_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL-1-I1_S4_L004_R1_001.fastq.gz -2 ~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL-1-I1_S4_L001_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL-1-I1_S4_L002_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL-1-I1_S4_L003_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL-1-I1_S4_L004_R2_001.fastq.gz -S CTRL_1mine.sam
echo "Finished aligning CTRL_1"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL-2-I2_S3_L001_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL-2-I2_S3_L002_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL-2-I2_S3_L003_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL-2-I2_S3_L004_R1_001.fastq.gz -2 ~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL-2-I2_S3_L001_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL-2-I2_S3_L002_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL-2-I2_S3_L003_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL-2-I2_S3_L004_R2_001.fastq.gz -S CTRL_2mine.sam
echo "Finished aligning CTRL_2"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL-3-I3_S2_L001_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL-3-I3_S2_L002_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL-3-I3_S2_L003_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL-3-I3_S2_L004_R1_001.fastq.gz -2 ~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL-3-I3_S2_L001_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL-3-I3_S2_L002_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL-3-I3_S2_L003_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL-3-I3_S2_L004_R2_001.fastq.gz -S CTRL_3mine.sam
echo "Finished aligning CTRL_3"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL-4-I4_S1_L001_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL-4-I4_S1_L002_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL-4-I4_S1_L003_R1_001.fastq.gz,~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL-4-I4_S1_L004_R1_001.fastq.gz -2 ~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL-4-I4_S1_L001_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL-4-I4_S1_L002_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL-4-I4_S1_L003_R2_001.fastq.gz,~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL-4-I4_S1_L004_R2_001.fastq.gz -S CTRL_4mine.sam
echo "Finished aligning CTRL_4"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFWT-1-I5_S12_L001_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFWT-1-I5_S12_L002_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFWT-1-I5_S12_L003_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFWT-1-I5_S12_L004_R1_001.fastq.gz -2 ~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFWT-1-I5_S12_L001_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFWT-1-I5_S12_L002_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFWT-1-I5_S12_L003_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFWT-1-I5_S12_L004_R2_001.fastq.gz -S BRAFwt_1mine.sam
echo "Finished aligning BRAFwt_1"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFWT-2-I6_S11_L001_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFWT-2-I6_S11_L002_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFWT-2-I6_S11_L003_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFWT-2-I6_S11_L004_R1_001.fastq.gz -2 ~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFWT-2-I6_S11_L001_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFWT-2-I6_S11_L002_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFWT-2-I6_S11_L003_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFWT-2-I6_S11_L004_R2_001.fastq.gz -S BRAFwt_2mine.sam
echo "Finished aligning BRAFwt_2"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFWT-3-I7_S10_L001_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFWT-3-I7_S10_L002_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFWT-3-I7_S10_L003_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFWT-3-I7_S10_L004_R1_001.fastq.gz -2 ~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFWT-3-I7_S10_L001_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFWT-3-I7_S10_L002_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFWT-3-I7_S10_L003_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFWT-3-I7_S10_L004_R2_001.fastq.gz -S BRAFwt_3mine.sam
echo "Finished aligning BRAFwt_3"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFWT-4-I8_S9_L001_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFWT-4-I8_S9_L002_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFWT-4-I8_S9_L003_R1_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFWT-4-I8_S9_L004_R1_001.fastq.gz -2 ~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFWT-4-I8_S9_L001_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFWT-4-I8_S9_L002_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFWT-4-I8_S9_L003_R2_001.fastq.gz,~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFWT-4-I8_S9_L004_R2_001.fastq.gz -S BRAFwt_4mine.sam
echo "Finished aligning BRAFwt_4"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/V600E/BV600E_1_I9-49197317/BV600E-1-I9_S8_L001_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_1_I9-49197317/BV600E-1-I9_S8_L002_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_1_I9-49197317/BV600E-1-I9_S8_L003_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_1_I9-49197317/BV600E-1-I9_S8_L004_R1_001.fastq.gz -2 ~/RNAseq/V600E/BV600E_1_I9-49197317/BV600E-1-I9_S8_L001_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_1_I9-49197317/BV600E-1-I9_S8_L002_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_1_I9-49197317/BV600E-1-I9_S8_L003_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_1_I9-49197317/BV600E-1-I9_S8_L004_R2_001.fastq.gz -S V600E_1mine.sam
echo "Finished aligning V600E_1"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/V600E/BV600E_2_I10-49203211/BV600E-2-I10_S7_L001_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_2_I10-49203211/BV600E-2-I10_S7_L002_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_2_I10-49203211/BV600E-2-I10_S7_L003_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_2_I10-49203211/BV600E-2-I10_S7_L004_R1_001.fastq.gz -2 ~/RNAseq/V600E/BV600E_2_I10-49203211/BV600E-2-I10_S7_L001_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_2_I10-49203211/BV600E-2-I10_S7_L002_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_2_I10-49203211/BV600E-2-I10_S7_L003_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_2_I10-49203211/BV600E-2-I10_S7_L004_R2_001.fastq.gz -S V600E_2mine.sam
echo "Finished aligning V600E_2"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/V600E/BV600E_3_I11-49201291/BV600E-3-I11_S6_L001_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_3_I11-49201291/BV600E-3-I11_S6_L002_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_3_I11-49201291/BV600E-3-I11_S6_L003_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_3_I11-49201291/BV600E-3-I11_S6_L004_R1_001.fastq.gz -2 ~/RNAseq/V600E/BV600E_3_I11-49201291/BV600E-3-I11_S6_L001_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_3_I11-49201291/BV600E-3-I11_S6_L002_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_3_I11-49201291/BV600E-3-I11_S6_L003_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_3_I11-49201291/BV600E-3-I11_S6_L004_R2_001.fastq.gz -S V600E_3mine.sam
echo "Finished aligning V600E_3"

hisat2 -p 16 --dta --no-softclip -x $hisat_index -1 ~/RNAseq/V600E/BV600E_4_I12-49200302/BV600E-4-I12_S5_L001_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_4_I12-49200302/BV600E-4-I12_S5_L002_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_4_I12-49200302/BV600E-4-I12_S5_L003_R1_001.fastq.gz,~/RNAseq/V600E/BV600E_4_I12-49200302/BV600E-4-I12_S5_L004_R1_001.fastq.gz -2 ~/RNAseq/V600E/BV600E_4_I12-49200302/BV600E-4-I12_S5_L001_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_4_I12-49200302/BV600E-4-I12_S5_L002_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_4_I12-49200302/BV600E-4-I12_S5_L003_R2_001.fastq.gz,~/RNAseq/V600E/BV600E_4_I12-49200302/BV600E-4-I12_S5_L004_R2_001.fastq.gz -S V600E_4mine.sam
echo "Finished aligning V600E_4"

 samtools sort -@ 16 -o CTRL_1mine.bam ~/RNAseq/CTRL_1mine.sam
echo "Finished sorting CTRL_1"

 samtools sort -@ 16 -o CTRL_2mine.bam ~/RNAseq/CTRL_2mine.sam
echo "Finished sorting CTRL_2"

 samtools sort -@ 16 -o CTRL_3mine.bam ~/RNAseq/CTRL_3mine.sam
echo "Finished sorting CTRL_3"

 samtools sort -@ 16 -o CTRL_4mine.bam ~/RNAseq/CTRL_4mine.sam
echo "Finished sorting CTRL_4"

 samtools sort -@ 16 -o BRAFwt_1mine.bam ~/RNAseq/BRAFwt_1mine.sam
echo "Finished sorting BRAFwt_1"

 samtools sort -@ 16 -o BRAFwt_2mine.bam ~/RNAseq/BRAFwt_2mine.sam
echo "Finished sorting BRAFwt_2"

 samtools sort -@ 16 -o BRAFwt_3mine.bam ~/RNAseq/BRAFwt_3mine.sam
echo "Finished sorting BRAFwt_3"

 samtools sort -@ 16 -o BRAFwt_4mine.bam ~/RNAseq/BRAFwt_4mine.sam
echo "Finished sorting BRAFwt_4"

 samtools sort -@ 16 -o V600E_1mine.bam ~/RNAseq/V600E_1mine.sam
echo "Finished sorting V600E_1"

 samtools sort -@ 16 -o V600E_2mine.bam ~/RNAseq/V600E_2mine.sam
echo "Finished sorting V600E_2"

 samtools sort -@ 16 -o V600E_3mine.bam ~/RNAseq/V600E_3mine.sam
echo "Finished sorting V600E_3"

 samtools sort -@ 16 -o V600E_4mine.bam ~/RNAseq/V600E_4mine.sam
echo "Finished sorting V600E_4"



 stringtie -p 16 -G $genes -o ~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL_1mine.gtf -l CTRL_1 ~/RNAseq/CTRL_1mine.bam
cp ~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL_1mine.gtf ~/RNAseq/CTRL_1mine.gtf
cp ~/RNAseq/CTRL_1mine.gtf ~/RNAseq/CTRL/CTRL_1_I1-49193365/CTRL_1mine.gtf
echo "Finished stringtie CTRL_1"

 stringtie -p 16 -G $genes  -o ~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL_2mine.gtf -l CTRL_2 ~/RNAseq/CTRL_2mine.bam
cp ~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL_2mine.gtf ~/RNAseq/CTRL_2mine.gtf
cp ~/RNAseq/CTRL_2mine.gtf ~/RNAseq/CTRL/CTRL_2_I2-49197319/CTRL_2mine.gtf 
echo "Finished stringtie CTRL_2"

 stringtie -p 16 -G $genes  -o ~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL_3mine.gtf -l CTRL_3 ~/RNAseq/CTRL_3mine.bam
cp ~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL_3mine.gtf ~/RNAseq/CTRL_3mine.gtf
cp ~/RNAseq/CTRL_3mine.gtf ~/RNAseq/CTRL/CTRL_3_I3-49190366/CTRL_3mine.gtf 
echo "Finished stringtie CTRL_3"

 stringtie -p 16 -G $genes  -o ~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL_4mine.gtf -l CTRL_4 ~/RNAseq/CTRL_4mine.bam
cp ~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL_4mine.gtf ~/RNAseq/CTRL_4mine.gtf
cp ~/RNAseq/CTRL_4mine.gtf ~/RNAseq/CTRL/CTRL_4_I4-49199313/CTRL_4mine.gtf 
echo "Finished stringtie CTRL_4"

 stringtie -p 16 -G $genes  -o ~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFwt_1mine.gtf -l BRAFwt_1 ~/RNAseq/BRAFwt_1mine.bam
cp ~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFwt_1mine.gtf ~/RNAseq/BRAFwt_1mine.gtf
cp ~/RNAseq/BRAFwt_1mine.gtf ~/RNAseq/BRAFwt/BRAFWT_1_I5-49192334/BRAFwt_1mine.gtf 
echo "Finished stringtie BRAFwt_1"

 stringtie -p 16 -G $genes  -o ~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFwt_2mine.gtf -l BRAFwt_2 ~/RNAseq/BRAFwt_2mine.bam
cp ~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFwt_2mine.gtf ~/RNAseq/BRAFwt_2mine.gtf
cp ~/RNAseq/BRAFwt_2mine.gtf ~/RNAseq/BRAFwt/BRAFWT_2_I6-49192335/BRAFwt_2mine.gtf 
echo "Finished stringtie BRAFwt_2"

 stringtie -p 16 -G $genes  -o ~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFwt_3mine.gtf -l BRAFwt_3 ~/RNAseq/BRAFwt_3mine.bam
cp ~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFwt_3mine.gtf ~/RNAseq/BRAFwt_3mine.gtf
cp ~/RNAseq/BRAFwt_3mine.gtf ~/RNAseq/BRAFwt/BRAFWT_3_I7-49189375/BRAFwt_3mine.gtf 
echo "Finished stringtie BRAFwt_3"

 stringtie -p 16 -G $genes  -o ~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFwt_4mine.gtf -l BRAFwt_4 ~/RNAseq/BRAFwt_4mine.bam
cp ~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFwt_4mine.gtf ~/RNAseq/BRAFwt_4mine.gtf
cp ~/RNAseq/BRAFwt_4mine.gtf ~/RNAseq/BRAFwt/BRAFWT_4_I8-49200298/BRAFwt_4mine.gtf 
echo "Finished stringtie BRAFwt_4"

 stringtie -p 16 -G $genes  -o ~/RNAseq/V600E/BV600E_1_I9-49197317/V600E_1mine.gtf -l V600E_1 ~/RNAseq/V600E_1mine.bam
cp ~/RNAseq/V600E/BV600E_1_I9-49197317/V600E_1mine.gtf ~/RNAseq/V600E_1mine.gtf
cp ~/RNAseq/V600E_1mine.gtf ~/RNAseq/V600E/BV600E_1_I9-49197317/V600E_1mine.gtf 
echo "Finished stringtie V600E_1"

 stringtie -p 16 -G $genes  -o ~/RNAseq/V600E/BV600E_2_I10-49203211/V600E_2mine.gtf -l V600E_2 ~/RNAseq/V600E_2mine.bam
cp ~/RNAseq/V600E/BV600E_2_I10-49203211/V600E_2mine.gtf ~/RNAseq/V600E_2mine.gtf
cp ~/RNAseq/V600E_2mine.gtf ~/RNAseq/V600E/BV600E_2_I10-49203211/V600E_2mine.gtf 
echo "Finished stringtie V600E_2"

 stringtie -p 16 -G $genes  -o ~/RNAseq/V600E/BV600E_3_I11-49201291/V600E_3mine.gtf -l V600E_3 ~/RNAseq/V600E_3mine.bam
cp ~/RNAseq/V600E/BV600E_3_I11-49201291/V600E_3mine.gtf ~/RNAseq/V600E_3mine.gtf
cp ~/RNAseq/V600E_3mine.gtf ~/RNAseq/V600E/BV600E_3_I11-49201291/V600E_3mine.gtf 
echo "Finished stringtie V600E_3"

 stringtie -p 16 -G $genes  -o ~/RNAseq/V600E/BV600E_4_I12-49200302/V600E_4mine.gtf -l V600E_4 ~/RNAseq/V600E_4mine.bam
cp ~/RNAseq/V600E/BV600E_4_I12-49200302/V600E_4mine.gtf ~/RNAseq/V600E_4mine.gtf
cp ~/RNAseq/V600E_4mine.gtf ~/RNAseq/V600E/BV600E_4_I12-49200302/V600E_4mine.gtf
echo "Finished stringtie V600E_4"





 stringtie --merge -p 16 -G $genes  -o ~/RNAseq/stringtie_mergedmine.gtf ~/RNAseq/mergelistmine.txt
echo "Finished merging"




  gffcompare -r $genes  -G -o ~/RNAseq/gffcompare/merged ~/RNAseq/stringtie_mergedmine.gtf
 echo "Finished gffcompare"




  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/CTRL_1mine.gtf ~/RNAseq/CTRL_1mine.bam
 echo "Finished stringtie to ballgown CTRL_1"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/CTRL_2mine.gtf ~/RNAseq/CTRL_2mine.bam
 echo "Finished stringtie to ballgown CTRL_2"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/CTRL_3mine.gtf ~/RNAseq/CTRL_3mine.bam
 echo "Finished stringtie to ballgown CTRL_3"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/CTRL_4mine.gtf ~/RNAseq/CTRL_4mine.bam
 echo "Finished stringtie to ballgown CTRL_4"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/BRAFwt_1mine.gtf ~/RNAseq/BRAFwt_1mine.bam
 echo "Finished stringtie to ballgown BRAFwt_1"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/BRAFwt_2mine.gtf ~/RNAseq/BRAFwt_2mine.bam
 echo "Finished stringtie to ballgown BRAFwt_2"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/BRAFwt_3mine.gtf ~/RNAseq/BRAFwt_3mine.bam
 echo "Finished stringtie to ballgown BRAFwt_3"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/BRAFwt_4mine.gtf ~/RNAseq/BRAFwt_4mine.bam
 echo "Finished stringtie to ballgown BRAFwt_4"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/V600E_1mine.gtf ~/RNAseq/V600E_1mine.bam
 echo "Finished stringtie to ballgown V600E_1"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/V600E_2mine.gtf ~/RNAseq/V600E_2mine.bam
 echo "Finished stringtie to ballgown V600E_2"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/V600E_3mine.gtf ~/RNAseq/V600E_3mine.bam
 echo "Finished stringtie to ballgown V600E_3"

  stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/V600E_4mine.gtf ~/RNAseq/V600E_4mine.bam
 echo "Finished stringtie to ballgown V600E_4"
"

**Comment by Jiglov** [comment]
Any help?

**Comment by JMF47** [comment]
Good timing. I just got back from my trip. I have some comments:

1) It might be best if you script the processing into a for loop. Typing everything out can be error prone.

2) The way you have structured these types of commands:
```
stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/V600E_4mine.gtf ~/RNAseq/V600E_4mine.bam
```
overwrites the `.ctab` file every time you run a different sample, because they all get saved to `~/RNAseq/ballgown'`. What you need is something like:
```
stringtie -e -B -p 16 -G ~/RNAseq/stringtie_mergedmine.gtf -o ~/RNAseq/ballgown/sample_V600E_4mine/output.gtf ~/RNAseq/V600E_4mine.bam
```
This is based on the documentation for stringtie:
```
-B 
This switch enables the output of Ballgown input table files (*.ctab) containing coverage data for the reference transcripts given with the -G option. (See the Ballgown documentation for a description of these files.) With this option StringTie can be used as a direct replacement of the tablemaker program included with the Ballgown distribution. 
If the option -o is given as a full path to the output transcript file, StringTie will write the *.ctab files in the same directory as the output GTF.
```

3) After that, you can run call

```
bg = ballgown(dataDir='~/RNAseq/ballgown', samplePattern='sample')
```

**Comment by Jiglov** [comment]
Thanks, trying it right now.

I'm aware of non-beauty of the code and the preference of the for loops, that was the shortest way to accomplish the task, following the published protocol.

I will improve it at some point...

I'll come back to you with the results....
