### ISSUE TITLE
time course design and command confermation

### ISSUE THREAD

**Issue by yangming** [alyssafrazee/ballgown#139]
Hi, all professionals!
     I have some confuse here in performing timecourse analysis of my samples. here is my expdesign, did I run a correct command for the time course analysis. Thank you all!
my design:
[exp_time_de.txt](https://github.com/alyssafrazee/ballgown/files/1878557/exp_time_de.txt)
the header of the design matrix is ::
```
IDs               tissue       reps     time     timen
xxxx_L0-1    shoot         1            0         1
xxxx_L0-2    shoot         2            0         1
xxxx_L0-3    shoot         3            0         1
xxxx_L05-1    shoot         1            0.5       2
xxxx_L05-2    shoot         2           0.5       2
xxxx_L05-3    shoot         3            0.5       2
...
```

my command is:
`tissue_adj_timecourse_transcript = stattest(bg, feature="transcript", meas='FPKM', covariate='time', timecourse=TRUE, adjustvars='tissue')`
 I want to compare the differences among the different time poits, and also the differences between two tissues (shoot and root) along the timecourse. Is this right?  which covariate is better, 'time' or 'timen'?   if I don't add the adjustvars, does the command mix all samples from the same time point (combining all reads or assemblies of shoot and root with 3 replicates from, say, time point 0.5h) and comparing to find the differences?
thanks again!

**Comment by JMF47** [comment]
Hi @yangming, since this is a analysis question and not an actual bug, could you please post the question to https://support.bioconductor.org. Thanks!
