### ISSUE TITLE
BALLGOWN

### ISSUE THREAD

**Issue by marasodi** [alyssafrazee/ballgown#142]
Hi 

Im am doing a project on RNA Seq, and will like to check differentially expressed genes. The data is between 2 genotypes, at 4 time points, treated and untreated samples all in 3 replicates. How do I go about such data because I'm not sure as to whether what I'm doing is right.

Thanks in advance

**Comment by alyssafrazee** [comment]
Hey, glad you're finding ballgown useful! This repo is for reporting bugs with the ballgown software. For help with analysis, we recommend posting on support.bioconductor.org with details about your analysis for online help. Best of luck!
