### ISSUE TITLE
Feature request: subset does not handle exon and intron expression

### ISSUE THREAD

**Issue by DaChip** [alyssafrazee/ballgown#147]
I have been getting an error when performing stattest:
Error in solve.default(t(mod) %*% mod) :
  system is computationally singular: reciprocal condition number =
This happens in particular when performing a stattest for differential exon expression:
```
bg_data_filt_e <- ballgown::subset(bg_data, "rowVars(eexpr(bg_data, meas='mcov')) > 1", genomesubset=TRUE)
results_exons <-  stattest(bg_data_filt_e, feature='exon', covariate='Condition' , `meas='mcov')
```
I have looked at results_exons and it appears as if my filter using eexpr is not actually working in the context of the condition argument. Similarly it does not appear as if you can filter intron expression either (using rowVars(iexpr... ).

If I want to filter exon expression measurements to remove low variance/low expression exons is there another way to do it?
I am trying to export the exon expression data (using eexpr) and filter on low variance (not in a ballgown object). I was thinking I could then perform stattest using the gowntable argument. Since I am very new to R I am finding this difficult, not least because during filtering I am losing rownames which contain the e_id (exon ids).
I've also posted on bioconductor forums: https://support.bioconductor.org/p/112824/#112917

**Comment by alyssafrazee** [comment]
Hi there, thanks for the note! I responded on Bioconductor with a workaround that should unblock you. 

Currently ballgown is maintenance mode only (bugfixes only, no new features) but if developers do eventually pick things back up, I've marked this as a feature request so someone can take it on (and for anyone reading, pull requests are welcome!).

**Comment by DaChip** [comment]
Hi Alyssa. Thanks for the comment. I have added a reply on bioconductor forums as I am still experiencing difficulties with my stattest. If you have time to take a look that would be much appreciated.

**Comment by DaChip** [comment]
Ok I have it working with filtering on variance prior to using the gowntable method. Thanks for your help!
