### ISSUE TITLE
DESeq2

### ISSUE THREAD

**Issue by Mithil15** [alyssafrazee/ballgown#149]
Hello, I am doing RNA-seq analysis,  using [https://www.ncbi.nlm.nih.gov/pubmed/27560171](url)  after StringTie quantification step, I have decided to useDESeq2 package(count-based methods) for Differential expression analysis[http://ccb.jhu.edu/software/stringtie/index.shtml?t=manual#deseq] and using the following commands:
`python2.7 ./prepDE.py -i sample_list.txt`

But every time I am facing an error
`Traceback (most recent call last):
  File "./prepDE.py", line 274, in <module>
    my_writer.writerow(geneDict[i])
  File "/usr/lib/python2.7/csv.py", line 152, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
ValueError: I/O operation on closed file
`
Since I don't know python I couldn't be able to solve this issue.

my sample_list file contains:
Treatment1 ./path/to/.gtf/file/which/is/obtained/from/stringtie/reestimation
Treatment2 ./path/to/.gtf/file/which/is/obtained/from/stringtie/reestimation
Control1 ./path/to/.gtf/file/which/is/obtained/from/stringtie/reestimation
.
.
. and so on
The output which i am getting is transcript_count_matrix.csv and gene_count_matrix.csv
from which gene_count_matrix.csv doesn't contain any values except first row:gene_id and Treatment1, Treatment2, Control1,etc

Any help in this regard will be deeply appreciated.

**Comment by alyssafrazee** [comment]
Hi there, `prepDE.py` is not part of ballgown -- it looks to be provided by the StringTie group. (It looks like you're not using ballgown in your workflow? DESeq2 takes the place of ballgown). According to the StringTie docs (http://ccb.jhu.edu/software/stringtie/index.shtml, under "Licensing and Contact Info"), they'd like bug reports https://github.com/gpertea/stringtie, so I'd suggesting posting there.

Thanks!
