### ISSUE TITLE
functional annotations/ gene ontology  after ballgown

### ISSUE THREAD

**Issue by fatimarasool** [alyssafrazee/ballgown#156]
Hi, I am working on wheat transcriptome RNA seq  data. I have successfully find the differentially expressed genes by ballgown. now I want to do Gene ontology. I have tried different tools for gene ontology but I could not got gene ontology results on my data. 

The list of genes is named as 

`TraesCS7B02G346700 

 TraesCS7A02G446900 

 TraesCS7D02G436800

 TraesCS2A02G309300

 TraesCS2B02G326400

 TraesCS2D02G307600

 TraesCS3A02G442000
 
 TraesCS3B02G475800

  TraesCS3B02G486000

  TraesCS3A02G449300

`  
I just show few genes above. these genes are not recognize in any tool. I have tries AgriGo, David  and Enrichr .
Can any one help me how I can I perform the gene ontology step?

**Comment by alyssafrazee** [comment]
Hi there, this is not an issue with ballgown, so I'm going to close this issue. The gene names come from the assembly software used to provide ballgown input, so I suggest looking for ontology resources by getting information on where the ballgown input came from in the first place. Thanks!
