### ISSUE TITLE
DESEQ2

### ISSUE THREAD

**Issue by tshori** [alyssafrazee/ballgown#165]
I just want to mention that unless I am missing something, you cannot not run DESeq or DeSeq2, as mentioned in the README, using the results from *expr, as the cov option gives you normalized counts and DESeq expects integers.  You could round the counts, but that somehow sounds like a terrible idea to me. I could be missing something.

**Comment by alyssafrazee** [comment]
Hey @tshori there are several other exon-level measurements available in the expr object (from tablemaker), including for example `rcount` and `ucount`. Both those measurements are count data (unlike `cov`) and would be suitable for DESeq2. Reference: https://github.com/alyssafrazee/ballgown/blob/master/README.md#ballgown-readable-expression-output (see first set of sub bullets).

Hope this helps!
