### ISSUE TITLE
running landsat linkr on Rstudio

### ISSUE THREAD

**Issue by brendachepngetich** [alyssafrazee/ballgown#167]
Hello guys i have been trying to run landsat linkr on my r studio and it keeps giving me this error 'Error in file(file, "rt") : invalid 'description' argument". Anyone who has an idea what cud be the problem please help me

**Comment by alyssafrazee** [comment]
Hi there, this repository has nothing to do with landsat linkr. I hope you were able to get your issue solved elsewhere!
