### ISSUE TITLE
Error with subset when doing filtering step

### ISSUE THREAD

**Issue by huajiachicat** [alyssafrazee/ballgown#168]
Hello:

I recently encounter a problem in filtering step. Running on test dataset (extdata/bg) is completely fine, but when running same code on own dataset it doesn't work:

Here is the phenotype csv file I have uploaded.

> id,colony,toxin,time
> R1B8-1,R1,Bt,8
> R1B8-2,R1,Bt,8
> R1B8-3,R1,Bt,8
> R1B16-1,R1,Bt,16
> R1B16-2,R1,Bt,16
> R1B16-3,R1,Bt,16
> R1O8-1,R1,Iso,8
> R1O8-2,R1,Iso,8
> R1O8-3,R1,Iso,8
> R1O16-1,R1,Iso,16
> R1O16-2,R1,Iso,16
> R1O16-3,R1,Iso,16
> R2B8-1,R2,Bt,8
> R2B8-2,R2,Bt,8
> R2B8-3,R2,Bt,8
> R2B16-1,R2,Bt,16
> R2B16-2,R2,Bt,16
> R2B16-3,R2,Bt,16
> R2O8-1,R2,Iso,8
> R2O8-2,R2,Iso,8
> R2O8-3,R2,Iso,8
> R2O16-1,R2,Iso,16
> R2O16-2,R2,Iso,16
> R2O16-3,R2,Iso,16
> S1B8-1,S1,Bt,8
> S1B8-2,S1,Bt,8
> S1B8-3,S1,Bt,8
> S1B16-1,S1,Bt,16
> S1B16-2,S1,Bt,16
> S1B16-3,S1,Bt,16
> S1O8-1,S1,Iso,8
> S1O8-2,S1,Iso,8
> S1O8-3,S1,Iso,8
> S1O16-1,S1,Iso,16
> S1O16-2,S1,Iso,16
> S1O16-3,S1,Iso,16
> S2B8-1,S2,Bt,8
> S2B8-2,S2,Bt,8
> S2B8-3,S2,Bt,8
> S2B16-1,S2,Bt,16
> S2B16-2,S2,Bt,16
> S2B16-3,S2,Bt,16
> S2O8-1,S2,Iso,8
> S2O8-2,S2,Iso,8
> S2O8-3,S2,Iso,8
> S2O16-1,S2,Iso,16
> S2O16-2,S2,Iso,16
> S2O16-3,S2,Iso,16

I use following command to load and filter data:

_library(ballgown)
library(RSkittleBrewer)
library(genefilter)
library(dplyr)
library(devtools)
pheno_data = read.csv("../34_35_phenodata.csv")
b= as.vector(pheno_data$id)
expression = ballgown(b, pData=pheno_data)
expression_filt = subset(expression, "rowVars(texpr(expression)) > 1", genomesubset = TRUE)_

Then I have following error messages:

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘texpr’ for signature ‘"function"’

I run the same code on test dataset, it works fine. Does anybody know what is the issue from?

Thanks

~Z

> sessionInfo()
> 
> R version 3.5.1 (2018-07-02)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: CentOS Linux 7 (Core)
> 
> Matrix products: default
> BLAS: /cluster/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/r-3.5.1-4vqz4egfxeegbrkbsw2wedqi4qfmg7cx/rlib/R/lib/libRblas.so
> LAPACK: /cluster/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/r-3.5.1-4vqz4egfxeegbrkbsw2wedqi4qfmg7cx/rlib/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] devtools_2.2.2     usethis_1.5.1      dplyr_0.8.5        genefilter_1.64.0 
> [5] RSkittleBrewer_1.1 ballgown_2.14.1   
> 
> loaded via a namespace (and not attached):
>  [1] Biobase_2.42.0              pkgload_1.0.2              
>  [3] bit64_0.9-7                 splines_3.5.1              
>  [5] assertthat_0.2.1            stats4_3.5.1               
>  [7] blob_1.2.1                  GenomeInfoDbData_1.2.0     
>  [9] Rsamtools_1.34.1            remotes_2.1.1              
> [11] sessioninfo_1.1.1           pillar_1.4.3               
> [13] RSQLite_2.2.0               backports_1.1.5            
> [15] lattice_0.20-35             glue_1.3.2                 
> [17] limma_3.38.3                digest_0.6.25              
> [19] GenomicRanges_1.34.0        RColorBrewer_1.1-2         
> [21] XVector_0.22.0              Matrix_1.2-14              
> [23] XML_3.99-0.3                pkgconfig_2.0.3            
> [25] zlibbioc_1.28.0             purrr_0.3.3                
> [27] xtable_1.8-4                processx_3.4.2             
> [29] BiocParallel_1.16.6         tibble_2.1.3               
> [31] annotate_1.60.1             mgcv_1.8-24                
> [33] IRanges_2.16.0              ellipsis_0.3.0             
> [35] withr_2.1.2                 SummarizedExperiment_1.12.0
> [37] BiocGenerics_0.28.0         cli_2.0.2                  
> [39] survival_2.42-3             magrittr_1.5               
> [41] crayon_1.3.4                memoise_1.1.0              
> [43] ps_1.3.2                    fs_1.3.2                   
> [45] fansi_0.4.1                 nlme_3.1-137               
> [47] pkgbuild_1.0.6              tools_3.5.1                
> [49] prettyunits_1.1.1           matrixStats_0.56.0         
> [51] S4Vectors_0.20.1            DelayedArray_0.8.0         
> [53] AnnotationDbi_1.44.0        callr_3.4.2                
> [55] Biostrings_2.50.2           compiler_3.5.1             
> [57] GenomeInfoDb_1.18.2         rlang_0.4.5                
> [59] grid_3.5.1                  RCurl_1.98-1.1             
> [61] tcltk_3.5.1                 bitops_1.0-6               
> [63] testthat_2.3.2              DBI_1.1.0                  
> [65] R6_2.4.1                    GenomicAlignments_1.18.1   
> [67] rtracklayer_1.42.2          bit_1.1-15.2               
> [69] rprojroot_1.3-2             desc_1.2.0                 
> [71] parallel_3.5.1              sva_3.30.1                 
> [73] Rcpp_1.0.4                  vctrs_0.2.4                
> [75] tidyselect_1.0.0

**Comment by alyssafrazee** [comment]
I think the issue is that you've named your ballgown object `expression` which is already a variable in R:

```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> expression
function (...)  .Primitive("expression")
```

I don't exactly know the order of operations for evaluation, but it sounds like ballgown is attempting to do `texpr(expression)` and finding the primitive `expressions` rather than your ballgown object. Can you try renaming it? For example, to `expression_data`? Like below:

```r
library(ballgown)
library(RSkittleBrewer)
library(genefilter)
library(dplyr)
library(devtools)
pheno_data = read.csv("../34_35_phenodata.csv")
b= as.vector(pheno_data$id)
expression_data = ballgown(b, pData=pheno_data)
expression_filt = subset(expression_data, "rowVars(texpr(expression_data)) > 1", genomesubset = TRUE)
```

**Comment by huajiachicat** [comment]
Thanks! problem solved!
