### ISSUE TITLE
 Error in file(file, "rt") : invalid 'description' argument 

### ISSUE THREAD

**Issue by tringa86** [alyssafrazee/ballgown#171]
Hi, I am wondering if you can help me out with this issue.
I am writing an R function that reads a directory full of files and reports the number of completely observed cases in each data file.

So I've created the function that returns the mean, and Is working but..

ollutantmean <- function(directory, pollutant, id= 1:332){
  filelist <- list.files(path = directory, pattern = "csv", full.names = TRUE)
  values <- numeric()
  
  for (i in id) {
    
    data<- read.csv(filelist[i])
      values <- c(values, data[[pollutant]])
    
}
      mean(values, na.rm = TRUE)
}

pollutantmean("C:/Users/tberisha/Documents/rprog_data_specdata/specdata", "sulfate")

when I try to get the sulfate from 1:10 

pollutantmean("specdata", "sulfate", 1:10) 

I get this error message  

Error in file(file, "rt") : invalid 'description' argument

**Comment by alyssafrazee** [comment]
Hi there! This is a spot to report problems with the `ballgown` R package. There isn't any ballgown code in your above example, so I'd suggest asking this question on StackOverflow or a similar site that can help with general debugging issues. Feel free to open another issue if you find a bug in ballgown specifically. Good luck!
