### ISSUE TITLE
NA values on varRows(texpr(bgControl1))- unable to get transcripts from ballgown object

### ISSUE THREAD

**Issue by lakshmi9c** [alyssafrazee/ballgown#172]
I created a ballgown object bgControl1 that has 181466 transcripts and 1 sample.
```
bgControl1
ballgown instance with 181466 transcripts and 1 samples
```

When I try to subset by removing low abundance genes by below command, I get 0 transcripts because rowVars function is always giving NA values.

```
bg_filt_control1 = subset(bgControl1,"rowVars(texpr(bgControl1)) >1",genomesubset=TRUE)
bg_filt_control1
ballgown instance with 0 transcripts and 1 samples
```

As you see rowVars() doesn't work for me. It gives NA values throughout for all transcripts!!
```
rowVars(texpr(bgControl1))
   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17 
  NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA   NA
```
The evaluation of `texpr(bgControl1)` is as below, if it helps:

```
head(texpr(bgControl1))
  FPKM.control1
1      0.180553
2      5.070339
3      2.871347
4      0.026413
5      0.056796
6      0.000000
```
Please help me fix it as I'm unable to progress. Is there any other way to calculate variance in my case? Thanks

**Comment by alyssafrazee** [comment]
Hi there, unfortunately variance is undefined for a vector of length 1 (you can't measure variation if you definitionally don't have any variation in your sample). To do statistical analysis (e.g. with stattest) I'm afraid you'll need to collect more replicates. You could still do exploratory analysis between the control replicate and treatment replicate, though you won't be able to get things like p-values and confidence intervals with only 1 sample per group.

**Comment by lakshmi9c** [comment]
Hi, thank you so much for your reply!
However, I do have these queries after my progress:

1. Is it necessary to remove low variance transcripts while doing differential gene expression? And why?
2. Why do we need to remove low gene abundance & low variance transcripts?
3. How do I get gene name and gene id without stattest() function on R using ballgown?
Thanks in advance
