### ISSUE TITLE
Help menu for ballgown constructor

### ISSUE THREAD

**Issue by BJWiley233** [alyssafrazee/ballgown#176]
FYI on the manual for `ballgown-constructor.Rd` under `Details` it says to use `file.path(path = dataDir, pattern = samplePattern) to see the sample order if \code{samples} was not used.` but I think you mean to say `list.files(path = dataDir, pattern = samplePattern)` as `file.path` gives the file path for pattern but the constructor really calls `list.files` and this is how you would confirm the order.

**Comment by alyssafrazee** [comment]
Thanks for the note. Fixed in https://github.com/alyssafrazee/ballgown/commit/7f0224c75201469e2078f88e6214e7b37f51c71a! (and the change to the actual Rd file was pushed in my more general docs cleanup in https://github.com/alyssafrazee/ballgown/commit/0375c781cf32d2f9c7e3bab45bc383249a4a4286).
