### ISSUE TITLE
How to calculate Fold Change (getFC) values in Ballgown?

### ISSUE THREAD

**Issue by mentorlg** [alyssafrazee/ballgown#177]
Hi
I have a question about Fold Change value from Ballgown.

I'm trying to calculate FC, p value, q value using 'stattest' in Ballgown.
and, I want to do stattest between 'type' (treat vs control)

1. My data set : 
> sample <- c("CANN_heat-3h-1", "CANN_heat-3h-2", "CANN_heat-3h-3", "CANN_control-3h-1", "CANN_control-3h-2", "CANN_control-3h-3")
> type <- c("heat", "heat", "heat", "a_control", "a_control", "a_control")

> pheno_data<-data.frame("id"=id, "type"=type)

2.  Read expression data from StringTie result
> bg <- ballgown(dataDir = "heat_3h", samplePattern = "CANN", pData=pheno_data)

(filtering out)
> bg_filt = subset(bg, "rowVars(texpr(bg)) >1", genomesubset=TRUE)

3. stat test
> stat_results = stattest(bg, feature='gene', covariate="type", getFC=TRUE, meas="FPKM")

As the results, I got FC values, pval, and qval.
Question) I wonder how FC values calculated in Ballgown..!
Before using Ballgown, I calculated FC values like 
1. 3 replicate -> average of 3 rep's FPKM
2. 'treat (FPKM+1) / control (FPKM+1)'    (plus 1 : because of zero FPKM)
but, it was different with Ballgown's FC results.
so, I want to know how calculate FC values in Ballgown.

kindly help, thank you :)
Amelia

**Comment by alyssafrazee** [comment]
Good question, and I apologize this isn't documented more clearly. The ballgown fold change from `getFC` is the value of the coefficient `beta1` in the linear model that ballgown fits for transcript expression. Specifically, the model for each transcript is `log(expression + 1) = beta0 + beta1 * type`. (In `stattest`, this model is compared to the model `log(expression + 1) = beta2` and the p- and q-values come from an F-test comparing the 2 models, i.e., from determining whether the model including `type` is actually better and thus that `type` influences expression). 

The fold changes are `exp(beta1)` which, given the interpretation of linear models where the outcome variable is on the log scale, represents the estimated fold change between types.

Hope this helps! For more details, see our paper in [Nature Biotech](https://www.nature.com/articles/nbt.3172) or if you don't have a subscription to that journal, there is a [preprint](https://www.biorxiv.org/content/10.1101/003665v2) that should also contain most of the relevant details.

**Comment by xingjianfeng100** [comment]
Hi,
I found something strange when I perform variation analysis using `stattest`. The gene MesC3160029059.g looks like down-regulation based on Fold Change, but the result of fpkm  flatly contradict it; the gene MesC3090015421.g looks like slightly up-regulation based on FPKM, but the result of Fold Change suggest the gene was up-regulated drastically, see table below for details. Could you please help solve the problem? Thank you!
![image](https://user-images.githubusercontent.com/34566522/223954663-7c32f158-478f-48a9-ac98-73189644210b.png)
