### ISSUE TITLE
biocLite("Biostrings") issue

### ISSUE THREAD

**Issue by kstatebioinfo** [alyssafrazee/ballgown#26]
There is a typo in the spelling of Biostrings. The "s" should not be capitalized on this page https://github.com/alyssafrazee/ballgown/blob/master/polyester/README.md

-Thanks

**Comment by alyssafrazee** [comment]
sample data set now available with ballgown as of bioconductor release august 2014

**Comment by kstatebioinfo** [comment]
Thanks I'll check it out
-J
