### ISSUE TITLE
Handling replicates in ballgown

### ISSUE THREAD

**Issue by Delasa** [alyssafrazee/ballgown#53]
Hello,
How can I specify different replicates for each sample in Ballgown? I have a time-course study with wild- type and mutant. For each sample I have three replicates. 
I see that in manual you have mentioned pData(bg) = data.frame(id=sampleNames(bg), group=rep(c(1,0), each=10)), which would be for distinguishing different groups such as WT and MT. However, I could not find anything in manual or Github for replicate handling in ballgown. What should my pData look like for a time-course for WT and Mutant with three replicates? Thanks.

**Comment by alyssafrazee** [comment]
If you have technical replicates, I would suggest having an "id" column and a "replicate" column in pData so it's clear each sample has multiple replicates. 

The default statistical models assume independence across all samples in the data set. A few strategies for dealing with replicates/correlated observations in the statistical DE models are:  
* collapse expression values across replicates (e.g., use the mean across replicates for each sample as that sample's expression measure). With this strategy the default stat models in ballgown are valid.
* fit a more complex model allowing for correlation within samples (e.g., random effects model). This will need to be done by hand and nested model comparison is much more complex than the implemented parametric F-test.
* use just one replicate for each sample, which unfortunately involves ignoring some data

In your scenario, it looks like you don't have much biological variation within group at all. (3 WT tech reps + 3 mutant tech reps). If you are just comparing 2 groups with 3 reps per group, the default models should work fine, but the variability estimated will be purely technical and likely smaller in magnitude than the variability you might observe in an experiment with biological replicates within group.

Hope this helps.

**Comment by Delasa** [comment]
Thanks for your reply. Sorry, I should have made myself more clear about my experiment. I have a time-course for WT and a time-course for mutant, and for each time-point I have 3 replicates:
WT time-course: d7a, d7b, d7c; d8a, d8b, d8c; ..., d17a, d17b, d17c
MT time-course:  d7a, d7b, d7c; d8a, d8b, d8c; ..., d17a, d17b, d17c

It seems that collapsing expression (solution 1) values using mean is the simplest way. But it would ignore cross-replicate dispersion.
Have you ever compared statical testing results of ballgown in a study with replicates with Cuffdiff? 

Can you guide me through solution 2 a little bit? How can I implement it using ballgown objects? 

Solution 3 does not seem to be a legitimate option, as it ignores replicates completely.

**Comment by alyssafrazee** [comment]
Cuffdiff is not designed for timecourse studies (its timecourse option does pairwise comparisons between timepoints 1-2, 2-3, etc.). We did do comparisons with Cuffdiff in case-control study designs with biological in [our manuscript](http://www.nature.com/nbt/journal/v33/n3/full/nbt.3172.html) ([free preprint here](http://biorxiv.org/content/early/2014/09/05/003665)). 

Ballgown simply provides the data in useful format for solution 2 (e.g., "texpr(bg)" gives you the transcript-by-sample expression matrix with columns in the same order as rows of pData). Statistical models beyond nested linear model comparisons are not built in (but you can get quite far with linear model comparisons). If you wanted to fit e.g. mixed models you would need to write your own code that fit such a model for each transcript.

**Comment by evilxsystems** [comment]
Can you please provide an example of collapsing multiple biological replicates loaded into a ballgown (your strategy 1) and then generating differential expression data (say two groups (10 replicates of two treatments) from your built in dataset of 100 transcripts and 20 samples)?  This is a very common experimental practice that seems entirely missing in the documentation.  I really love the speed and lower memory consumption of hisat2 and stringtie but the inability to handle experimental replicates seems like an oversight in ballgown.
