### ISSUE TITLE
Issue with stattest

### ISSUE THREAD

**Issue by srithegreat** [alyssafrazee/ballgown#54]
I get the following error when I try running stattest

Error in quantile.default(lognz, 0.75) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

How can I remove the NaNs from the bg before doing stattest?

**Comment by alyssafrazee** [comment]
If you have missing values in the ballgown object, you should think carefully about why they are missing and what to do with these values. You could use the "subset" function to drop transcripts or samples with missing values, or you could replace the missing values and reassign texpr/eexpr/iexpr. I stress that the decision about what to do with missing values is critical and could have a good amount of impact on downstream results. 

If you are getting missing values/NAs from tablemaker, please file an issue on the [tablemaker repository](https://github.com/alyssafrazee/tablemaker) and I can follow up with the primary developer on tablemaker about why that might have happened.
