### ISSUE TITLE
 unused argument (sampleNames = sample_IDs)

### ISSUE THREAD

**Issue by charlin90** [alyssafrazee/ballgown#55]
Hi,I have a question whiling making the ballgown object using function "samples",it is giving an error " unused argument (sampleNames = sample_IDs)",why? 
In my run,
sample_IDs "NT.0345dde4-90c6-4c5e-ae82-562eccb652da","NT.03f64293-0f12-4aec-a1de-1dfd295ea95b",etc.
Thanks a lot
Charlin

**Comment by alyssafrazee** [comment]
Hey Charlin, thanks for reporting this! Could you please post the exact command you ran when you got this error as well as the output of sessionInfo()? I will try to get to the bottom of this. code you tired t

**Comment by charlin90** [comment]
My run command::
> setwd("/public/wangzl/RNA-Seq-raw/bin")
> library(ballgown)

Attaching package: ‘ballgown’

The following object is masked from ‘package:base’:

    structure

> data=read.table("liver.txt",row.names=1)
> sample_IDs = rownames(data)
> sample_paths = paste0('/public/wangzl/RNA-Seq-raw/bin/', sample_IDs, '/stringtie')
> bg = ballgown(samples=sample_paths, sampleNames=sample_IDs, meas='all')
Error in ballgown(samples = sample_paths, sampleNames = sample_IDs, meas = "all") : 
  unused argument (sampleNames = sample_IDs)
Execution halted

That's all.

**Comment by alyssafrazee** [comment]
Ah, I see what's happening. If you check out the docs for the ballgown function (?ballgown), you'll see that sampleNames is not an argument to the ballgown function. 

You can extract sample IDs from ballgown objects with the sampleNames _function_, i.e., sampleNames(bg). But you cannot change the sampleNames (because they are used as a sanity check throughout the package to make sure everything is in the right order).

**Comment by charlin90** [comment]
Ah，that means，the given example code about function “samples” is not fully correct.
Example code:
sample_IDs = c('oneSample', 'anotherSample', 'aThirdSample')
sample_paths = paste0('/home/', sample_IDs, '/ballgown')
sample_paths

## [1] "/home/oneSample/ballgown"
## [2] "/home/anotherSample/ballgown"
## [3] "/home/aThirdSample/ballgown"

bg = ballgown(samples=sample_paths, sampleNames=sample_IDs, meas='all')
There is seemly a misleading for users and I suggest to revise it.
Thank you for your good answer.

**Comment by alyssafrazee** [comment]
Aha! Good catch in the docs, thanks! We were having some discussion about how this should work--and it looks like we updated the documentation too soon. I'm deleting that example.
