### ISSUE TITLE
ballgown vs cuffdiff

### ISSUE THREAD

**Issue by charlin90** [alyssafrazee/ballgown#56]
Hi,I have got the primary results of ballgown for differential expression analysis.There is seemly a large gap between ballgown and cuffdiff.Notably,ballgown output ~14000 significant distinct expressed transcripts,nearly two times relatived to cuffdiff(~8000).However,there is only a small overlap including ~2700 transcripts,and their fold changes evaluated are considerably distinct.For all significant distinct transcripts from ballgown,the fold changes are generally several times(1-10);while cuffdiff results present hundreds of fold changes(1-1000).I am confusing about these results,and I don't know which results are more close to true difference.Can you help me?Notably,expression values were caculated by stringtie software instead of Tablemaker.
Thanks a lot
Charlin

**Comment by charlin90** [comment]
I further analyzed the output results from ballgown,I have several questions:
1.When set "log=FALSE",I find the some difference values were not correponding to FC values,for example,transcript A FC>1,yet difference<0,I think there should be consistent,that is to say,difference>0.
2.I extracted fpkm values across all samples using ballgown.And I manually caculated two-group means without normalization respectivly.It is weird that some differences I manually caculated are not consistent with the results from ballgown.For example,difference>0(manually) while that<0(ballgown).Although through normalization in ballgown,I simply think,there also should be consistent(up-regulation or down-regulation).
3.According to given instructions,all fpkm values are log2 transformed and normalized default.So output fc values don't represent the true difference between two groups,it is seemly not useful.Although we can optionlly obtain the difference values,but it is seemly not ideal for estimating expression variance.
Above all,I can obtain significantly distinctly expressed genes,but I seemly can't correctly justfy which genes are up-regulated or down-regulated.I feel the given log2FC in cuffdiff or limma is good and clear.Why ballgown don't adopt this?
I am very confused for these results,and I desperately need your help.
Thank you very much.

**Comment by alyssafrazee** [comment]
* We have shown in our manuscript (http://www.nature.com/nbt/journal/v33/n3/full/nbt.3172.html, e.g. supplementary note 5) that ballgown and cuffdiff produce different results and that ballgown's results are more liberal. You will need to choose which software is more appropriate for your study.

* In fitting models, FPKM values are log-transformed and normalized, but the model coefficient output is exponentiated. (So it is an "adjusted fold change"). This should be useful for many purposes.

* Unfortunately we haven't experienced the sign inconsistencies you're describing, and I'm not able to debug without further information. If you think there's a problem with ballgown's code, please email me your entire script as well as your ballgown object in rda format, and I will try to see if I can reproduce the problem and fix the bug.
