### ISSUE TITLE
How to interpret the pictures of the presults？

### ISSUE THREAD

**Issue by tiramisutes** [alyssafrazee/ballgown#57]
![image](https://cloud.githubusercontent.com/assets/10768210/7005509/fd09ff0e-dcaa-11e4-9e56-4c6f15d6fc66.png)

**Comment by jtleek** [comment]
These plots show the transcript structure for a particular gene and sample, colored by their expression level. So this is locus XLOC_000454, which has three transcripts, the genomic position is the x-axis and the level of expression in sample 12 is shown by color.

**Comment by tiramisutes** [comment]
Thank you very much for you help.
