### ISSUE TITLE
Determine alternative splicing between samples

### ISSUE THREAD

**Issue by PeterVenhuizen** [alyssafrazee/ballgown#59]
I was wondering whether it is possible to determine alternative splicing between samples with Ballgown. With cuffdiff there is the splicing.diff output file, but so far I could only find information on transcript differential expression and not something for transcript differential splicing between samples.

Thanks in advance!

**Comment by alyssafrazee** [comment]
There isn't a built-in way to do differential splicing in ballgown. You could use limma instead: fit linear models on each row of the exon count table (eexpr(bg) in ballgown), then use the [diffSplice](http://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/limma/html/diffSplice.html) function to test for differential splicing.

**Comment by PeterVenhuizen** [comment]
Could you give me a little help in how to do this? I have been looking at the limma manual and so far I have been able to find out that I should do:
* bg <- ballgown(samples=c('WT','OX'), meas='all')
* fit <- lmFit(eexpr(bg), c(0, 1))
* ex <- diffSplice(fit, geneID="GeneID")
and than I could get the top differentially spliced genes with topSplice etc. 
However, I have a problem with the geneID vector required by diffSplice. The eexpr data frame has the expression data for all samples per exon, but how do I link the exons back to the genes, so that I can produce the geneID vector for diffSplice?

**Comment by alyssafrazee** [comment]
You can use the indexes component of a ballgown object to do this:

```R
transcript_id_by_exon = indexes(bg)$e2t$t_id #exon/transcript mapping
transcript_id_by_gene = indexes(bg)$t2g$t_id #transcript/gene mapping
geneID = indexes(bg)$t2g$g_id[match(t_by_exon, t_by_gene)]
```

I know this is a little roundabout; I'll file an issue on the repo so that we can possibly make this a bit friendlier to do. (But this should give you what you want in the meantime!)

**Comment by PeterVenhuizen** [comment]
Thanks for the quick reply, it helped me a lot. However, I had to make a small adjustment to your code, because I encountered the following error:
```R
Error in `$<-.data.frame`(`*tmp*`, "GeneID", value = c(1L, 1L, 1L, 1L,  : 
replacement has 475148 rows, data has 243924
```
The `transcript_id_by_exon` vector you generate contains (some) duplicate values for the exon id's, where as the `eexpr(bg)` data frame has only one entry per exon. Therefore the `geneID` vector contains is too long. I changed the code to this:
```R
transcript_id_by_exon = indexes(bg)$e2t$t_id[match(unique(indexes(bg)$e2t$e_id), indexes(bg)$e2t$e_id)]
transcript_id_by_gene = indexes(bg)$t2g$t_id #transcript/gene mapping
geneID = indexes(bg)$t2g$g_id[match(transcript_id_by_exon, transcript_id_by_gene)]
```
and now everything seems to work fine.

**Comment by pradeepphule** [comment]
how to visualize differeential splicing , i tried using plotsplice() function from limma after executiong above code for my data but it do not show logfc value correctly also start position is missing in the plot.

**Comment by alyssafrazee** [comment]
hi there, differential splicing visualization is not part of ballgown, unfortunately! I would recommend checking out the splicing visualization libraries in limma instead!
