### ISSUE TITLE
stringtie can not work if the bam file larger than 4GB?

### ISSUE THREAD

**Issue by chgyi** [alyssafrazee/ballgown#63]
i did human RNA seq.first map them to hg19 use hisat. And then use the samtools view and sort to get the sorted bam.but if the sorted bam file is larger than 4GB, i can not get the gtf file .it stoped at the gtf.tmp files.

**Comment by alyssafrazee** [comment]
From this description, the most likely problem is that you're running out of disk space. Closing issue since ballgown is not involved here.

**Comment by chgyi** [comment]
my disk is 6T. And it is almost empty. Thank you！
