### ISSUE TITLE
getGenes example doesn't work

### ISSUE THREAD

**Issue by filicado** [alyssafrazee/ballgown#64]
with
geneoverlaps = getGenes(gtfPath, structure(bg)$trans, UCSC=FALSE)

I get:

Error in getGenes(gtfPath, structure(bg)$trans, UCSC = FALSE) : 
  unused argument (UCSC = FALSE)

Since I'm simply trying the example from the documentation I assume this must be a bug...

**Comment by alyssafrazee** [comment]
Unfortunately I can't reproduce this error -- to help me debug further, could you please provide all the lines of code you tried to run and the complete error message, plus the output of `sessionInfo()`? Thanks!
