### ISSUE TITLE
without replicates

### ISSUE THREAD

**Issue by mencent** [alyssafrazee/ballgown#65]
Hi,
We have samples without replicates. How to use ballgown to analyze data? Ballgown  might not be able to export unique counts for transcript or gene. The iexpr and eexpr can export ucount for introns and exons.

**Comment by alyssafrazee** [comment]
All expression measurements for transcripts, genes, introns, and exons can be calculated with one replicate per sample (including rcount, ucount, mrcount, etc). These metrics involve counting sequencing reads overlapping each feature, and this is done on for each sample (using tablemaker for the easiest integration with ballgown). 

If you have no replicates in the _experiment_ (i.e., you just have one sample / one replicate) you will not be able to do statistical analysis that requires estimating variance, i.e., you won't be able to use `stattest`.

Please see the readme / vignette for more information about analyzing data with ballgown.

**Comment by jtleek** [comment]
I would just add that if you want you can rank the genes/transcripts by fold change by calculating log2(FPKM_rep1) - log2(FPKM_rep2). But without replicates *you can not perform statistical inference* so you can't calculate p-values, confidence intervals, standard errors or anything like that. This is true for Ballgown and any other software you might use for this problem. 

Hope that helps!

jeff
