### ISSUE TITLE
seqinfo: 12333 sequences from an unspecified genome

### ISSUE THREAD

**Issue by northbio** [alyssafrazee/ballgown#66]
After I run
structure(bg)

I got the following info
seqinfo: 12333 sequences from an unspecified genome ;  no seqlengths

How can I get the name of the 12333 sequences???

**Comment by alyssafrazee** [comment]
I believe you can get the names with `seqnames(structure(bg))`, although I'm not 100% sure -- I'd recommend reading the [GenomicRanges documentation](http://bioconductor.org/packages/release/bioc/html/GenomicRanges.html) for this. (The structure component of a ballgown object is a `GRangesList`, so you should be able to use all available methods for that class on that component).
