### ISSUE TITLE
a problem about       stattest

### ISSUE THREAD

**Issue by northbio** [alyssafrazee/ballgown#67]
Hi, I　encountered a problem when I run the following command:
stat_results13 = stattest(bg_group13, feature='gene', meas='FPKM', covariate='group')

the error info are as follows:
Error in quantile.default(lognz, 0.75) :
  missing values and NaN's not allowed if 'na.rm' is FALSE
In addition: Warning message:
In tlengths \* tmeas :
  longer object length is not a multiple of shorter object length

However, no problem happend when I　run a similiar command 
stat_results13 = stattest(bg_group13, feature='transcript', meas='FPKM', covariate='group')

can anyone tell me why? how to find the missing info in the bg................

**Comment by jtleek** [comment]
It appears that there may be some trouble in obtaining the gene counts. Can you give us a little more information? Are there NA values, missing values, negative values in your count matrix? Have you built the ballgown object with the corresponding gtf file? 

Also any session information you can give would be really helpful.

**Comment by northbio** [comment]
First, I got my expression data from tablemaker and then input the five table in each sample into ballgown. After I put this question, I exported all genes' the expression data by 
gene_expression = gexpr(bg)
and check gene_expression. A lot of strange data was found, just like:
XLOC_034030 NA Inf Inf Inf Inf Inf Inf Inf NA
XLOC_034068 NA NA NA NA NA NA Inf NA NA
XLOC_034069 Inf Inf Inf Inf Inf NA Inf Inf Inf
I don't know where these "Inf" and "NA" came from........can you tell the difference between the two?

I also checked t_data.ctab file in one of my samples, and got the expression value of all transcripts. But nither "Inf" nor "NA" was found in t_data.ctab ....

Another question:  Now I want to use subset in Ballgwon to get these genes don't have "Inf" or "NA". But after I saw the help info like this:
bg_twogenes = subset(bg, "gene_id=='XLOC_000454' | gene_id=='XLOC_000024'")
I still don't know how to extract only 10,000 genes I  interested in my data. 
Can anyone help me in this? Thanks in advance.

**Comment by jtleek** [comment]
This appears to be a problem with the annotation. It looks like the
transcript data are being correctly calculated, but that the annotation for
the genes doesn't match somehow. What software did you use to assemble the
transcriptome?

**Comment by northbio** [comment]
StringTie. 
Now I encountered another problem which is in the end of my reply. I used the following command:
bg_tengenes = subset(bg, "gene_id == 'XLOC_034440'| gene_id=='XLOC_034443' | gene_id=='XLOC_034444' | gene_id=='XLOC_034445'| gene_id=='XLOC_034447'| gene_id=='XLOC_034449'")
and got what I want.
but if I put the gene names in a table file with each name in a row, I don't know how to get the same result, can you help me with it ?

**Comment by alyssafrazee** [comment]
If you have the gene names in a file, read the file into a data frame, then use the right data frame column in your subset expression:

```
name_df = read.table('gene_file_name')
name_column = name_df[,1]
bg_tengenes = subset(bg, "gene_id %in% name_column")
```

You may also get better help with this more general type of R question on the Bioc support forum: (support.bioconductor.org, can tag with "ballgown" for specific ballgown help).

**Comment by northbio** [comment]
I encountered another STRANGE problem when I run:
stat_bg2_results12 = stattest(bg2_group12, feature='gene', meas='FPKM', covariate='group')
Error in solve.default(t(mod) %*% mod) :
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0

the data was got by 
bg2 = subset(bg, "gene_id == 'XLOC_006528' | gene_id =='XLOC_006529'")
pData(bg2) = data.frame(id=sampleNames(bg2), group=rep(c(1,2,3), each=3))
bg2_group12 = subset(bg2, "group == 1 | group == 2", genomesubset=FALSE)

and the gene structure was as follows in T02/t_data.ctab:
98550   scaffold1341    .       105588  105864  TCONS_00014386  1       277     XLOC_006528             0       0
112138  scaffold13413   -       354     800     TCONS_00014387  2       356     XLOC_006529             35.6718 5.56266

HOWEVER, If I use stattest with this two genes and other genes, it will work out the pval and qval without error info......
what should I do now?

**Comment by DarrellL** [comment]
Hi, thanks for the program.

I'm also getting the same error when trying to run stattest on my full ballgown object:
> stat_results = stattest(gown=bg, feature='transcript', meas='FPKM', covariate='group')
Error in solve.default(t(mod) %*% mod) : 
  system is computationally singular: reciprocal condition number = 2.01225e-41

or when using gene:
> stat_results = stattest(bg, feature='gene', meas='FPKM', covariate='group')
Error in solve.default(t(mod) %*% mod) : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0

Up to the stattest, bg is behaving as expected, able to output t2g tables etc (except for the error identified in issue #72).

I'd appreciate any ideas / help.

**Comment by jtleek** [comment]
Hi Darrell

Can you tell us what your design matrix looks like (mod?) it may be because
that is co-linear.

Cheers

Jeff

**Comment by alyssafrazee** [comment]
The "system is computationally singular" usually means that all samples have the same value (usually 0, or something very close to zero) for at least one transcript/gene. You can usually fix this by filtering by expression level (see ?exprfilter). 

[Jeff commented as I was typing- another way to say the same thing!]

**Comment by DarrellL** [comment]
Hi Alyssa & Jeff, thanks to both of you for the prompt reply

Yes, there were a lot of features with no expression across the samples. I have filtered these out as you recommend, but no luck with the stattest error:

> over100 = exprfilter(bg, cutoff=100, meas='FPKM')
> stat_results = stattest(over100, feature='gene', meas='FPKM', covariate='group')
Error in solve.default(t(mod) %*% mod) : 
  system is computationally singular: reciprocal condition number = 2.58359e-23

I am using the default design matrices. But running the code from the stattest function appears to produce the following for mod:
	(Intercept)	as.factor(x)1	libadjust
1	1	1	3051.303
2	1	1	3051.303
3	1	1	3051.303
4	1	0	3051.303
5	1	0	3051.303
6	1	0	3051.303

**Comment by jtleek** [comment]
Hi Darrell

That seems to be the problem. The column for the intercept and the library
adjustment are perfectly linearly dependent. I think the library adjustment
should be different for every sample?

Best

Jeff

**Comment by DarrellL** [comment]
Yup, looks like a problem with my input from StringTie (a typo in my iterative looping made all the outputs the same), hence the same library adjustment factor. Thanks for the help.
