### ISSUE TITLE
subset issue:Error in eval(expr, envir, enclos) : object 'geneid' not found

### ISSUE THREAD

**Issue by bcantarel** [alyssafrazee/ballgown#69]
I would like to make the geneid a variable, however when I use the subset function with this gene variable I get this error: Error in eval(expr, envir, enclos) : object 'geneid' not found

With Error:
geneid <- 'ENSG00000125538.8'
genebg <- subset(bg,"gene_id==geneid")

No Error:
genebg <-  subset(bg,"gene_id=='ENSG00000125538.8'")

If the first (with error) example is incorrect, please clarify the documenation.
Thanks!

**Comment by alyssafrazee** [comment]
In the first example, the function is literally looking for the gene called `geneid`. That variable isn't getting evaluated when it's a substring of a larger string. You will need to use string concatenation (i.e. the `paste` function) for the first example to work:

```
geneid <- 'ENSG00000125538.8'
genebg <- subset(bg, paste0("gene_id=='", geneid, "'"))
```

**Comment by bcantarel** [comment]
When I try this solution, I get the following error:

> genebg <- subset(bg,paste0("gene_id=='", geneid, "'"))
Loading required package: ballgown
Creating a generic function for 'nchar' from package 'base' in package 'S4Vectors'

Attaching package: 'ballgown'

The following object is masked from 'package:base':

    structure

Error in subset.default(bg, paste0("gene_id=='", geneid, "'")) : 
  'subset' must be logical
> paste0("gene_id=='", geneid, "'")
[1] "gene_id=='ENSG00000163661.3’"
