### ISSUE TITLE
can not loading the ballgown library to R 

### ISSUE THREAD

**Issue by chgyi2015** [alyssafrazee/ballgown#73]
my system is mint linux ,and R 3.2.2.. Now i have installed the ballgown package.but when i library(ballgown), there have many problems such as" in method for ‘coerce’ with signature ‘"dgRMatrix","matrix.csr"’: no definition for class “matrix.csr”"
     if i ignore this warning ,when i use the example data do "bg = ballgown(dataDir=data_directory, samplePattern='sample', meas='all')" ,It returns "unable to find an inherited method for function ‘Rle’ for signature ‘"factor", "integer"’.
    now i do not know why ,anyone can help me ? thanks

**Comment by JMF47** [comment]
can you post what the command sessionInfo() shows?

**Comment by chgyi2015** [comment]
as belows ,thanks.
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ballgown_2.2.0

loaded via a namespace (and not attached):
 [1] AnnotationDbi_1.32.2       XVector_0.10.0            
 [3] GenomicRanges_1.22.2       BiocGenerics_0.16.1       
 [5] splines_3.2.2              zlibbioc_1.16.0           
 [7] GenomicAlignments_1.6.1    IRanges_2.4.6             
 [9] BiocParallel_1.4.3         xtable_1.8-0              
[11] lattice_0.20-33            GenomeInfoDb_1.6.1        
[13] tools_3.2.2                grid_3.2.2                
[15] SummarizedExperiment_1.0.1 parallel_3.2.2            
[17] nlme_3.1-122               Biobase_2.30.0            
[19] mgcv_1.8-10                DBI_0.3.1                 
[21] genefilter_1.52.0          lambda.r_1.1.7            
[23] futile.logger_1.4.1        survival_2.38-3           
[25] Matrix_1.2-3               sva_3.18.0                
[27] rtracklayer_1.30.1         RColorBrewer_1.1-2        
[29] S4Vectors_0.8.5            futile.options_1.0.0      
[31] bitops_1.0-6               RCurl_1.95-4.7            
[33] RSQLite_1.0.0              limma_3.26.3              
[35] Biostrings_2.38.2          Rsamtools_1.22.0          
[37] stats4_3.2.2               XML_3.98-1.3              
[39] annotate_1.48.0

**Comment by JMF47** [comment]
The packages required looks correct.
When you do:

`bg = ballgown(dataDir=data_directory, samplePattern='sample', meas='all')`

What is the value for `data_directory`?
What is the structure that you are storing the .ctab files that ballgown needs? Is it like:
data_directory/
    sample01/
        e2t.ctab
        e_data.ctab
        i2t.ctab
        i_data.ctab
        t_data.ctab
    sample02/
        e2t.ctab
        e_data.ctab
        i2t.ctab
        i_data.ctab
        t_data.ctab
    ...
    sample20/
        e2t.ctab
        e_data.ctab
        i2t.ctab
        i_data.ctab
        t_data.ctab

**Comment by chgyi2015** [comment]
i used the test data in the ballgown packages.  the result is lack below.
> bg = ballgown(dataDir=data_directory,samplePattern='sample',meas='all')
Sun Dec 27 14:04:52 2015
Sun Dec 27 14:04:52 2015: Reading linking tables
Sun Dec 27 14:04:52 2015: Reading intron data files
Sun Dec 27 14:04:52 2015: Merging intron data
Error in (function (classes, fdef, mtable)  : 
unable to find an inherited method for function ‘Rle’ for signature ‘"factor", "integer"’

**Comment by JMF47** [comment]
Can you run the code, get to the error, and run `traceback()` then post what the list of commands are?
Thanks

**Comment by chgyi2015** [comment]
Thanks.
> traceback()
8: stop(gettextf("unable to find an inherited method for function %s for signature %s", 
       sQuote(fdef@generic), sQuote(cnames)), domain = NA)
7: (function (classes, fdef, mtable) 
   {
       methods <- .findInheritedMethods(classes, fdef, mtable)
       if (length(methods) == 1L) 
           return(methods[[1L]])
       else if (length(methods) == 0L) {
           cnames <- paste0("\"", vapply(classes, as.character, 
               ""), "\"", collapse = ", ")
           stop(gettextf("unable to find an inherited method for function %s for signature %s", 
               sQuote(fdef@generic), sQuote(cnames)), domain = NA)
       }
       else stop("Internal error in finding inherited methods; didn't return a unique method", 
           domain = NA)
   })(list("factor", "integer"), function (values, lengths, ...) 
   standardGeneric("Rle"), <environment>)
6: Rle(values = value, lengths = runLength(x))
5: `runValue<-`(`*tmp*`, value = 1L)
4: `runValue<-`(`*tmp*`, value = 1L)
3: newGRanges("GRanges", seqnames = seqnames, ranges = ranges, strand = strand, 
       mcols = DataFrame(..., check.names = FALSE), seqlengths = seqlengths, 
       seqinfo = seqinfo)
2: GRanges(seqnames = Rle(intron$chr), ranges = IRanges(start = intron$start, 
       end = intron$end), strand = Rle(intron$strand), id = intron$i_id, 
       transcripts = tnamesin.ord)
1: ballgown(dataDir = data_directory, samplePattern = "sample", 
       meas = "all")

**Comment by alyssafrazee** [comment]
@JMF47 - I'll leave final resolution to you, but my guess is that this is a version issue with `GenomicRanges` (or maybe `IRanges`). I'm not sure what changed in the new release of Bioconductor, but I did notice that (a) the version of `GenomicRanges` used in the vignette is much lower than the poster's `GenomicRanges`, and the version of _ballgown_ (2.2.0) isn't the version here or in the ballgown-release repo. These `interited method` errors are often version things, and it's possible that the Rle stuff in the reader function has to be adapted to the updated `GenomicRanges` package. Let me know if I can be helpful here.

**Comment by JMF47** [comment]
@alyssafrazee I've replicated the package versions that the poster has (mainly targeting GenomicRanges_1.22.2 and ballgown_2.2.0) but still cannot replicate the problem. I have run into a similar issue before, where with identical package loadings, GRanges from GenomicRanges will throw a similar warning depending on how I call the GRanges() function. Let me keep looking into this.

**Comment by JMF47** [comment]
@chgyi2015 Let's try this:

Update R to version 3.2.3
Then run R and do
```
source("http://bioconductor.org/biocLite.R")
biocLite("BiocUpgrade")
```
Update all the BioC packages as prompted

Then reinstall ballgown using
```
source("http://bioconductor.org/biocLite.R")
biocLite("ballgown")
```

Let me know if that removes the package loading errors and ballgown creation errors.

**Comment by chgyi2015** [comment]
@JMF47 it is ok  when i updata to R 3.2.3 ,thanks.
