### ISSUE TITLE
Ballgown plotTranscripts function

### ISSUE THREAD

**Issue by matifr** [alyssafrazee/ballgown#75]
Hi everyone, 

I am using ballgown to measure transcript abundance in my RNA-seq samples. 
I want to plot the transcripts of a gene using the plotTranscript function of the ballgown package.

When i try to run:

    plotTranscripts(gene='DDX11L1', gown=bg, samples='sample3_output',meas='FPKM', colorby='transcript', main='transcripts from gene DDX11L1: sample 3, FPKM')
I get this error:

    Error in seq.default(min(gtrans$start), max(gtrans$end), by = 1) : 
    'from' cannot be NA, NaN or infinite
    In addition: Warning messages:
    1: In min(gtrans$start) : no non-missing arguments to min; returning Inf
    2: In max(gtrans$end) : no non-missing arguments to max; returning -Inf

I have no clue about what it means. Until that point everything was executed without errors/warnings.

Any help would be much appreciated!!

**Comment by matifr** [comment]
Sorry about the naive question, just realised that I had to use the ensembl gene_id instead of the gene name, thats why it couldn't find the range of the gene.

**Comment by jtleek** [comment]
No worries, hope it is all working onw?

**Comment by matifr** [comment]
Yes all working! 
Thanks a lot for the tool! Its great!

**Comment by rodrigojardim** [comment]
Hi all,

I was able to use plotTranscripts, but I don't understand the graph. Please, what do the bars and dotted lines mean? Where can I find explanatory documentation?

Thanks!

**Comment by alyssafrazee** [comment]
Documentation is here! https://github.com/alyssafrazee/ballgown#plotting-transcript-structures

The bars represent the expressed parts of the gene (colored by expression level, typically corresponding to exons). The dotted lines represent introns. Each row on the transcript plot corresponds to a different transcript of that gene (same underlying gene, but different expression formats).

**Comment by rodrigojardim** [comment]
Thank you so much!
Rodrigo Jardim


Em seg., 16 de out. de 2023 às 17:26, Alyssa Frazee <
***@***.***> escreveu:
