### ISSUE TITLE
last exon of a given transcript located before the first exon ?

### ISSUE THREAD

**Issue by gdoura** [alyssafrazee/ballgown#76]
I want to use the output of the ballgown object with the spliceR package. 
for that I need to construct a GRanges object for the transcripts:

**transcriptFeatures <- GRanges(
		seqnames=isoformChr,
		ranges=IRanges(
			start=isoformStart,
			end=isoformEnd),
		spliceR=isoformData[,-10]		#add spliceR to metadata colnames
	)
**

But when I do:
> structure(bg)trans[13] 

I have the following: 

**GRangesList object of length 1:
$13 
GRanges object with 5 ranges and 2 metadata columns:
      seqnames             ranges strand |        id transcripts
         <Rle>          <IRanges>  <Rle> | <integer> <character>
  [1]     chr1 [4777525, 4777648]      - |        24       11:14
  [2]     chr1 [4782568, 4782733]      - |        25       11:14
  [3]     chr1 [4783951, 4784105]      - |        26       11:13
  [4]     chr1 [4785573, 4785726]      - |        29       12:14
  [5]     chr1 [4773200, 4774516]      - |        30       13:14**

Here for the transcript#13, The last exon has genomic coordinate that put it before the first exon  
and thus the width of this transcript (txEnd-txStart) = 4774516-4777525 is negative, 
the range of this transcript cannot be coerced into a Granges object. 
but when I plot this transcript everything is in place. 

Am I missing something?

Thank you very much for your help.

Best regards,
AG

**Comment by JMF47** [comment]
Hey there, this has to do with the way ballgown stores all of the exons in a compact structure. Each unique exons gets an unique id as well as in which transcripts they will be found in. This process is done in a particular order. 



During processing, transcript 11 was processed first, and all of its exons evaluated. If an exon that tx11 has was already seen in tx1-10, then that information is added to the previously noted exon. If an exon was not previously seen in transcripts 1 through 10, then a new exon is identified, a new ID is issued, as well as information stored that it is seen in tx11. 

Repeat this process for each successive tx in the dataset, and you can see that exons are added to the list of unique exons based on the order they are seen in sequential transcripts. As a result, exon 30 showed up relatively late to the party - it is unique to tx13 and tx14, so it is recorded later than all the unique exons seen in tx1-12.

Thus, this requires a little post-processing to get results the way you would like. Simply do
```
exons = structure(bg)$trans[[13]]
exons = exons[order(start(exons))]
```
and you should have all the exon segments in order for whatever you wish to do.

Best,
Jack

**Comment by gdoura** [comment]
Hi Jack,
very clear explanation ! 
Thank you very much. 

Best regards,
AG
