### ISSUE TITLE
Documentation request.  Replicate handling 

### ISSUE THREAD

**Issue by evilxsystems** [alyssafrazee/ballgown#80]
Can you please provide an example of collapsing multiple biological replicates loaded into a ballgown (your strategy 1 in issue #53) and then generating differential expression data (say two groups (10 replicates of two treatments) from your built in dataset of 100 transcripts and 20 samples)? This is a very common experimental practice that seems entirely missing in the documentation. I really love the speed and lower memory consumption of hisat2 and stringtie but the inability to handle experimental replicates seems like an oversight in ballgown.  It is entirely possible that this is not discussed in the documentation because it is trivial to do in bg and that my R skills are lacking, but a little guidance would be appreciated.
Thanks.

**Comment by alyssafrazee** [comment]
This is documented extensively in ballgown's vignette, beginning: https://github.com/alyssafrazee/ballgown#indexes (this is the section of the ballgown object for experimental data), and the `pData` component is used throughout the other examples in the vignette.

See also https://support.bioconductor.org/p/79173/#81223 which I believe answers the same question.
