### ISSUE TITLE
No transcript name in stattest

### ISSUE THREAD

**Issue by wangdp123** [alyssafrazee/ballgown#81]
Hi,

I am trying to use Ballgown to detect the differential expression for transcript level but unfortunately when I perform the following command in R prompt, what I can get is only the transcript id but not the transcript name. But what I need is the exact and explicit transcript names in order to identify them.

The gtf file is from the one that has been used for Tophat.

stat_transcript_results = stattest(bg, feature='transcript', meas='FPKM', covariate='group', getFC = TRUE)

The example of the result I get:

"","feature","id","fc","pval","qval"
"7379","transcript","7379","4.303765e-01","7.700581e-07","0.008897031"
"26203","transcript","26203","9.700445e-01","7.830429e-07","0.008897031"
"37920","transcript","37920","3.355973e+00","1.271877e-06","0.008897031"
"47471","transcript","47471","3.244647e+01","7.081109e-07","0.008897031"
"48679","transcript","48679","2.449809e-01","1.225220e-06","0.008897031"
"28398","transcript","28398","3.187912e-01","1.763690e-06","0.010281139"
"38558","transcript","38558","3.962344e+00","2.751633e-06","0.013748733"
"1464","transcript","1464","2.788336e-01","3.191924e-06","0.013955093"

Could you please help me out about this?

Many thanks,

Regards,

Tom

**Comment by alyssafrazee** [comment]
Hi Tom, you can match the ids from the result of "stattest" using the columns of the transcript table: in `texpr(bg, 'all')`, the result will contain a column called `t_id` (matching the id column from the results of stattest) and a corresponding column called `t_name` which contains the transcript IDs from the GTF you provided (in your case, from tophat). You can use e.g. a join function from dplyr or the "match" function from base R to join that `t_name` column on to the results of stattest. Hope this helps!
