### ISSUE TITLE
The sum of FPKMs from transcripts is not equal to the FPKM of this gene 

### ISSUE THREAD

**Issue by wangdp123** [alyssafrazee/ballgown#82]
Hi,

I have performed the RNA-Seq analysis with HISAT - StringTie - Ballgown combination, and surprisingly, I found out that the sum of FPKMs from each transcript from one gene is not equal to (seems to be larger than) the FPKM value of this gene.

Do you think this is an ordinary observation? If not, how to work out this issue?

Many thanks,

With regards,

Tom

**Comment by alyssafrazee** [comment]
The sum of FPKMs per transcript is not necessarily the sum of the FPKMs for the gene (because of how FPKM is calculated, and specifically because of how it's denominated by the transcript length).
