### ISSUE TITLE
stattest for a single pair of samples

### ISSUE THREAD

**Issue by drvenki** [alyssafrazee/ballgown#84]
Hi Alyssa, 
This might not actually be a bug but I am finding it difficult to do a stattest for just one treated and one untreated sample here.

I may sound silly or perhaps missed out on something as well but I am unable to find any help or documentation regarding this one sample vs one sample analysis. 

I am stuck at the stat_results step. Here are the commands I used.

> pData(bg) = data.frame(id=sampleNames(bg), group=rep(c('T','UT'), each=1))
> pdata(bg)
               id group
1 sample01_output     T
2 sample02_output    UT
> stat_results = stattest(bg, feature='transcript', meas='FPKM', covariate='group')

And I get this ERROR 
"Error in stattest(bg, feature = "transcript", meas = "FPKM", covariate = "group",  : 
  There must be at least two replicates per group. Make sure covariate is categorical; if continuous, consider the timecourse option, or specify your own models with mod and mod0."

Is there any way I could run this for only one pair of samples? - Treated (T) and Untreated (UT) or am I getting something wrong?

Thanks in advance,
Venki

**Comment by alyssafrazee** [comment]
Hey Venki,

As the error message states, there must be at least two replicates per group.

Unfortunately you cannot perform statistical inference without replicates. If you want, you can rank the genes/transcripts by fold change, for example, by calculating log2(FPKM_rep1) - log2(FPKM_rep2), and you may be able to get some useful information that way! But without replicates, you can not perform statistical inference, so you can't calculate p-values, confidence intervals, standard errors or anything like that. (It does not make sense to estimate variability when you have only one item). This is true for Ballgown and any other software you might use for this problem (so you are correct that it isn't a bug in Ballgown :)). 

Good luck!
