### ISSUE TITLE
which difference do the differentialy expressed transcripts indicate? how to pick the data of TPM?

### ISSUE THREAD

**Issue by boya888** [alyssafrazee/ballgown#90]
which difference do the differentialy expressed transcripts indicate?

Take "Table 2 | Population and sex associated with each sample used in the protocol" in your NatureProtocol for example, 

results_transcripts = stattest(bg_chrX_filt,feature="transcript",covariate="sex",adjustvars =c("population"), getFC=TRUE, meas="FPKM")

 Which difference does the obtained FC (fold change) mean?

If we gonna to analyze the difference between the Female-GBR and Male-GBR, what shall we set the parameters?

If we gonna to analyze the difference between the Female-GBR and Male-YRI, what shall we set the parameters of covariate and adjustvars? 

Another point confused us is how to pick the data of TPM.

Since ballgown code mentioned TPM in

meas = match.arg(meas, c('TPM', 'FPKM', 'all'))

and the output of Stringtie only held t_data.ctab with cov and FPKM (Cufflinks-estimated FPKM for the transcript), but we can't obtain the TPM datamatrix using the parameter "all". After all, the GTF file (Cd1h-1.gtf) output by Stringtie has one column for "TPM" value, but lost in the file t_data.ctab.

transcript_data_frame = texpr(bg, 'all')

which output only contained cov and FPKM, and ignored "TPM", which we hungered for.

So we post our confusions here.

Thanks for your concern.

**Comment by alyssafrazee** [comment]
This was answered here: https://support.bioconductor.org/p/88159/#88625

This type of question is more appropriate for support.bioconductor.org (since it's not a technical problem with the ballgown package). The ballgown maintainers all read the support site (as do many more people!) so no need to file your question in both places :)
