### ISSUE TITLE
Ballgown not recognizing .ctab files 

### ISSUE THREAD

**Issue by ftkorkmaz** [alyssafrazee/ballgown#95]
I recently performed RNA seq analysis using HSAT and StringTie on Galaxy. Since the Galaxy public server does not offer Ballgown I am attempting to use R. I have exported a sample set of .ctab files from Galaxy and I am trying to load them into Ballgown, but get the following error: 

Error in ballgown(samples = "Users/filizkorkmaz/extdata/sample01") : 
  Something is wrong: are you missing .ctab files? Do extra files/folders (other than tablemaker output folders) match your samples/dataDir/samplePattern argument(s)?

Galaxy labels their StringTie output as tabular but I changed the file name to .ctab 

Can anyone help with this? Sorry if this a little naive but I am very new to this process. Thanks!

**Comment by alyssafrazee** [comment]
Hey @ftkorkmaz --

Could you please post:
1. the exact command you ran
2. the directory structure of the folder `Users/filizkorkmaz/extdata/sample01`
3. the directory structure of the folder `Users/filizkorkmaz/extdata`?

(you can see an example "directory structure" in the README: https://github.com/alyssafrazee/ballgown#loading-data-into-r)

My guess is that you need to pass `samples='/Users/filizkorkmaz/extdata` -- note the initial `/`, and the lack of `/sample01` at the end. I can't confirm my guess though without the above pieces of info :) so just let me know.

**Comment by ftkorkmaz** [comment]
Hi @alyssafrazee --
Thanks for your response and I apologize for my late response. I figured it out...definitely a newbie mistake! I didn't put the desktop into the directory structure.  (samples='/Users/filizkorkmaz/**desktop**/extdata). Anyways, thanks for your help...I'm still working on the differential analysis, had to take a few days to work on other projects. I'll post if I have more questions.

**Comment by alyssafrazee** [comment]
Great, glad it got sorted out! If you do have further questions about your analysis, please post them on support.bioconductor.org with the `ballgown` tag -- there's a wider variety of folks there to help with analysis, and we do watch that tag to make sure there aren't bugs in the package. Thanks!
