### ISSUE TITLE
Error: is.null(pData) | class(pData) == "data.frame" is not TRUE

### ISSUE THREAD

**Issue by ghost** [alyssafrazee/ballgown#99]
Hi, 
I'm using the 'Tuxedo' pipeline to analyze RNA-seq data. I'm stuck at the ballgown step. I've loaded the phenotype data, which looks like this:
"ids","treat"
"RNATREAT1","treatment"
"RNATREAT2","treatment"
"RNACTRL1","control"
"RNACTRL2","control"
with the following command:
pheno_data <- read.csv("./RNA_phenodata.csv")
and I get stuck with loading pData:
bg <- ballgown(dataDir = "ballgown", samplePattern="RNA", pData="pheno_data")
Mon Mar 13 18:38:16 2017
Mon Mar 13 18:38:16 2017: Reading linking tables
Mon Mar 13 18:38:17 2017: Reading intron data files
Mon Mar 13 18:38:21 2017: Merging intron data
Mon Mar 13 18:38:24 2017: Reading exon data files
Mon Mar 13 18:38:37 2017: Merging exon data
Mon Mar 13 18:38:41 2017: Reading transcript data files
Mon Mar 13 18:38:47 2017: Merging transcript data
**Error: is.null(pData) | class(pData) == "data.frame" is not TRUE**

Any ideas what might be going wrong?

**Comment by alyssafrazee** [comment]
yep - per the error message, pData has to be either NULL or a data frame.
you've passed "pheno_data", which is a string.

Try instead: `bg <- ballgown(dataDir = "ballgown", samplePattern="RNA",
pData=pheno_data)` (no quotes around pheno_data).

**Comment by swernig** [comment]
i tried that as well and it gives the same error.

**Comment by swernig** [comment]
That worked, thank you!

**Comment by ScroopieNoopers** [comment]
Alyssa! Please help!

I have the same issue as above, but no quotes around pheno_data, and I still get the error they got. 

> setwd("C:/Users/ogde923/stringtie-1.3.4d")
> pheno_data=("TomatoPheno.csv")
> bg_TomatoAnalysis = ballgown(dataDir = 'ballgown', samplePattern = 'Tom', pData=pheno_data)
Tue Oct 30 09:15:53 2018
Tue Oct 30 09:15:53 2018: Reading linking tables
Tue Oct 30 09:15:53 2018: Reading intron data files
Tue Oct 30 09:15:55 2018: Merging intron data
Tue Oct 30 09:15:55 2018: Reading exon data files
Tue Oct 30 09:15:59 2018: Merging exon data
Tue Oct 30 09:15:59 2018: Reading transcript data files
Tue Oct 30 09:16:00 2018: Merging transcript data
Error in ballgown(dataDir = "ballgown", samplePattern = "Tom", pData = pheno_data) : 
  is.null(pData) | class(pData) == "data.frame" is not TRUE

Directory structure 
C:\Users\ogde923\stringtie-1.3.4d\ballgown
contains files named
TomI9C1
TomI9C2
TomI9D1
TomI9D2
TomM8C1
TomM8C2
TomM8D1
TomM8D2

Each file contains only the .ctab files. 

The pheno_data file "TomatoPheno.csv" contains

ids | treatment
TomI9C1 | Control
TomI9C2 | Control
TomI9D1 | Drought
TomI9D2 | Drought
TomM8C1 | Control
TomM8C2 | Control
TomM8D1 | Drought
TomM8D2 | Drought

Thanks!
Aaron

**Comment by alyssafrazee** [comment]
You have `pheno_data=("TomatoPheno.csv")`, which means that `pheno_data` is literally the string `"pheno_data"`. You need to actually ready in the CSV file so pData is a data frame: `pheno_date = read.csv("TomatoPheno.csv")`.

**Comment by ScroopieNoopers** [comment]
Wow. What a rookie mistake. Okay. So new question. 

I'm reanalyzing another research group's dataset. They have two  biological replicates of "control" and two of "drought" (I know, only two  biological replicates in 2018...right?)

So I follow the Nature 2017 protocol, everything smooth (thanks for the previous help, I'm a dummy), until this step . 


> pheno_data=read.csv("Tom.csv") > bg_tom = ballgown(dataDir="ballgown1",samplePattern="Tom",pData=pheno_data) 
Tue Oct 30 12:55:02 2018 
Tue Oct 30 12:55:02 2018: Reading linking tables 
Tue Oct 30 12:55:03 2018: Reading intron data files 
Tue Oct 30 12:55:04 2018: Merging intron data 
Tue Oct 30 12:55:05 2018: Reading exon data files 
Tue Oct 30 12:55:11 2018: Merging exon data 
Tue Oct 30 12:55:12 2018: Reading transcript data files 
Tue Oct 30 12:55:12 2018: Merging transcript data 
Wrapping up the results 
Tue Oct 30 12:55:13 2018 
> bg_tom_filt = subset(bg_tom,"rowVars(texpr(bg_tom)) >1", genomesubset=TRUE) 
> results_transcripts=stattest(bg_tom_filt, feature="transcript",covariate="Cultivar",adjustvars=c("Treatment"), getFC=TRUE, meas="FPKM") 

Coefficients not estimable: TreatmentDrought  
Error in solve.default(t(mod) %*% mod) :    
      system is computationally singular: reciprocal condition number = 1.49681e-26 
In addition: Warning message: 
Partial NA coefficients for 17430 probe(s)


Thanks for getting back to me so quickly. You're the best.

**Comment by JMF47** [comment]
Can you show what the `phone_data` table looks like?
In particular, what is `Cultivar` and `Treatment`?
The output seems to indicate that there are no enough observations in one of the subgroups that get created by using those variables.

**Comment by alyssafrazee** [comment]
The `system is computationally singular` error is essentially a "divide by zero" error when doing linear regression. Your problem seems to be that you have both `covariate="Cultivar"` and `adjustvar="Treatment"` specified, but those are the same variables. (i.e., you only have CI9/Control and DI9/Drought -- those two columns aren't any different from a numerical perspective). 

You don't need to specify adjustvars if you don't have any, and it doesn't look like you do. I would think that removing adjustvars altogether will fix the issue (at least mathematically; I'd still be pretty skeptical/wary of results where you only have 2 samples in each group).
